[CmdletBinding()]
param([string]$ResearchPath='project-state/discovery/municipaldevelopment-agenda-minutes-cluster-research-2026-09-12.json',[string]$InventoryPath='project-state/master-inventory.json',[string]$OutputPath='project-state/discovery/municipaldevelopment-agenda-minutes-family-decision-2026-09-20.json')
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$research=Get-Content -Raw -Encoding UTF8 $ResearchPath|ConvertFrom-Json;$inventory=Get-Content -Raw -Encoding UTF8 $InventoryPath|ConvertFrom-Json;$byId=@{};foreach($r in $inventory.candidates){$byId[$r.id]=$r};$now=(Get-Date).ToUniversalTime().ToString('o')
foreach($item in $research.approved_for_addition){$r=$byId[$item.id];$raw=if($item.psobject.Properties.Name -contains 'raw_file_url'){$item.raw_file_url}else{$null};$orphan=($item.psobject.Properties.Name -contains 'preserved_under_the_missing_minutes_policy') -and $item.preserved_under_the_missing_minutes_policy;$r.status='approved for addition';$r.source_url=$item.authoritative_url;$r.direct_file_url=if($raw){$raw}else{$item.authoritative_url};$r.date=$item.date;$r.file_type='PDF';$r.size_bytes=[int64]$item.size_bytes;$r.checksum_sha256=$item.checksum_sha256;$r.title=$item.title;$r.description=$item.description;$r.description_word_count=$item.description_word_count;$r.proposed_canonical_page=$item.proposed_canonical_page;$r.provenance_status='Saved research directly fetched and measured the authoritative City PDF.';$r.validation_status='inventory-only agenda/minutes family decision; archive preparation pending authorization';$r.updated_at=$now;$q=[pscustomobject][ordered]@{visual_inspection=$item.evidence;measured_content="$($item.pages) pages; $($item.size_bytes) bytes; SHA-256 $($item.checksum_sha256).";standalone_public_value=if($orphan){'Limited but sufficient as the verified surviving official agenda after recorded exhaustive minutes review.'}else{'High: approved meeting minutes or a substantive meeting packet.'};information_density=if($item.pages -le 2){'Limited-content meeting-record exception documented by the family relationship.'}else{'Substantive packet or minutes record.'};series_component_relationship=if($orphan){'Agenda retained only under the missing-minutes policy and must be visibly labelled.'}else{'Minutes are retained in preference to their corresponding agenda where both exist.'};intended_publication_form='Inventory-only original pending authorized R2 archival and public-byte verification.';rationale='Current family reassessment retains the saved decision: approved minutes are primary records; only verified orphan agendas receive the explicit missing-minutes exception.'};if($r.psobject.Properties.Name -contains 'quality_assessment'){$r.quality_assessment=$q}else{$r|Add-Member NoteProperty quality_assessment $q};$r.processing_notes=@($r.processing_notes+"Family decision 2026-09-20: $($q.series_component_relationship)"|Select-Object -Unique)}
$all=@($research.approved_for_addition+$research.duplicate+$research.excluded);$records=foreach($item in $all){$r=$byId[$item.id];[ordered]@{id=$item.id;saved_recommendation=$item.recommended_status;current_status=$r.status;title=$r.title;missing_minutes_label=if($item.psobject.Properties.Name -contains 'label_required'){$item.label_required}else{$null};canonical_id=if($item.psobject.Properties.Name -contains 'canonical_id'){$item.canonical_id}else{$null};minutes_record=if($item.psobject.Properties.Name -contains 'minutes_record'){$item.minutes_record}else{$null}}}
$artifact=[ordered]@{schema_version=1;artifact_type='ordinary_queue_family_decision';recorded_at='2026-09-20';research_artifact=$ResearchPath;family=[ordered]@{name='Municipal Development agenda and minutes';scope_candidate_ids=@($all.id|Sort-Object);definition='AEC meeting minutes and verified orphan agendas, plus GAATC/GAATC-GARTC agenda records.'};dispositions=[ordered]@{approved_for_addition=@($research.approved_for_addition.id);duplicate=@($research.duplicate.id);excluded=@($research.excluded.id)};records=@($records);summary=[ordered]@{approved_for_addition=18;duplicate=1;excluded=7;requires_human_review=0};archive_gate='No R2 mutation or public content action; approved records need authorized archive/public-byte verification.';safeguards_observed=[ordered]@{r2_mutation=$false;public_content_changed=$false;merge_or_deploy=$false}}
$inventory.candidates=@($inventory.candidates|Sort-Object id);$counts=[ordered]@{};foreach($s in $inventory.allowed_statuses){$counts[$s]=@($inventory.candidates|Where-Object status -eq $s).Count};$inventory.counts=[pscustomobject]$counts;$pending=@('pending review','approved for addition','downloaded','parsed','description drafted','placement assigned');$eligible=@($inventory.candidates|Where-Object{$_.status -in $pending -or ($_.status -eq 'implemented' -and $_.validation_status -ne 'passed')}|ForEach-Object id|Sort-Object);$inventory.next_pending_id=$eligible[0];$inventory.generated_at=$now
foreach($pair in @(@($inventory,$InventoryPath),@($artifact,$OutputPath))){$tmp=([IO.Path]::GetFullPath($pair[1]))+'.tmp-'+$PID;[IO.File]::WriteAllText($tmp,($pair[0]|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false));Move-Item $tmp $pair[1] -Force};$artifact.summary|ConvertTo-Json
