[CmdletBinding()]
param(
  [string]$ResearchPath = 'project-state/discovery/meeting-agenda-documents-cluster-research-2026-09-11.json',
  [string]$InventoryPath = 'project-state/master-inventory.json',
  [string]$OutputPath = 'project-state/discovery/meeting-agenda-documents-closeout-2026-09-20.json'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
function Write-AtomicJson($Value, [string]$Path) {
  $temporaryPath = ([IO.Path]::GetFullPath($Path)) + ".tmp-$PID"
  try { [IO.File]::WriteAllText($temporaryPath, ($Value | ConvertTo-Json -Depth 20), [Text.UTF8Encoding]::new($false)); Move-Item -LiteralPath $temporaryPath -Destination $Path -Force }
  finally { if (Test-Path -LiteralPath $temporaryPath) { Remove-Item -LiteralPath $temporaryPath -Force } }
}
$research=Get-Content -Raw -Encoding UTF8 -LiteralPath $ResearchPath|ConvertFrom-Json
$inventory=Get-Content -Raw -Encoding UTF8 -LiteralPath $InventoryPath|ConvertFrom-Json
$byId=@{}; foreach($candidate in $inventory.candidates){$byId[$candidate.id]=$candidate}
$now=(Get-Date).ToUniversalTime().ToString('o')
$approved=$research.approved_for_addition[0]; $candidate=$byId[$approved.id]
$candidate.status='excluded'; $candidate.source_url=$approved.authoritative_url; $candidate.direct_file_url=$approved.authoritative_url; $candidate.date=$approved.date; $candidate.file_type='PDF'; $candidate.size_bytes=[int64]$approved.size_bytes; $candidate.checksum_sha256=$approved.checksum_sha256; $candidate.title=$approved.title; $candidate.agency='Committee on Guidelines for Negotiations'; $candidate.provenance_status='Saved research directly fetched and rendered the authoritative City PDF.'; $candidate.exclusion_reason='Current quality reassessment: although this PDF appends an adopted Open Meetings Act notice resolution to its agenda, it is a short procedural annual-notice instrument with no durable standalone public value under the current publication-quality standard.'; $candidate.validation_status='meeting-agenda closeout: excluded after current quality reassessment'; $candidate.updated_at=$now
$quality=[pscustomobject][ordered]@{visual_inspection='Saved research rendered the image-only three-page PDF and identified an agenda followed by the annual notice resolution.';measured_content='3 pages; 148,196 bytes; SHA-256 82807ff53ef7728b83f67a98aa148334a3bcce975aecdc72a3c018e238614c9b.';standalone_public_value='Low: procedural annual Open Meetings Act notice, rather than a substantive policy or program record.';information_density='Limited: meeting-notice mechanics and agenda material.';series_component_relationship='Not a meeting-minutes substitute and not a record of Council action on substantive business.';intended_publication_form='No standalone public entry.';rationale='The saved finding correctly identifies a resolution, but current standards reject short procedural administrative records without a limited-content exception.'}
if($candidate.psobject.Properties.Name -contains 'quality_assessment'){$candidate.quality_assessment=$quality}else{$candidate|Add-Member -NotePropertyName quality_assessment -NotePropertyValue $quality}
$candidate.processing_notes=@($candidate.processing_notes + 'Current quality reassessment changed saved approval to exclusion; this is a procedural notice resolution, not a substantive meeting record.' | Select-Object -Unique)
$canonical=$byId['src-ff9893ec1cd700be']; if(-not $canonical){throw 'Missing study-session canonical.'}; $canonical.status='excluded'; $canonical.exclusion_reason='Current meeting-record reassessment: one-page City Council study-session agenda contains no minutes, action record, or attached substantive material. It is excluded on the agenda-only quality ground; this does not assert that the meeting occurred or that minutes do not exist.'; $canonical.validation_status='meeting-agenda closeout: excluded agenda-only record'; $canonical.updated_at=$now; $canonical.processing_notes=@($canonical.processing_notes + 'Resolved with duplicate src-d5cfa0fec162e3c1 so the same agenda is decided once.' | Select-Object -Unique)
$all=@($research.approved_for_addition+$research.duplicate+$research.excluded)
$records=foreach($row in $all){$current=$byId[$row.id]; $canonicalId=if($row.psobject.Properties.Name -contains 'canonical_id'){$row.canonical_id}else{$null}; [ordered]@{id=$row.id;saved_recommendation=$row.recommended_status;current_status=$current.status;integration=if($row.id -eq $approved.id){'current_quality_reassessment_changed_saved_approval'}elseif($row.id -eq 'src-d5cfa0fec162e3c1'){'saved_duplicate_relationship_reused'}else{'saved_terminal_exclusion_reused'};authoritative_url=$row.authoritative_url;size_bytes=$row.size_bytes;checksum_sha256=$row.checksum_sha256;canonical_id=$canonicalId;reason=if($row.id -eq $approved.id){$current.exclusion_reason}elseif($row.id -eq 'src-d5cfa0fec162e3c1'){'Duplicate relationship retained exactly to src-ff9893ec1cd700be.'}else{'Saved terminal exclusion reused without renewed source research.'}}}
$artifact=[ordered]@{schema_version=1;artifact_type='meeting_agenda_family_closeout';recorded_at='2026-09-20';research_artifact=$ResearchPath;scope='All 20 IDs in the saved meeting-agenda-documents artifact, plus the linked study-session canonical required to preserve its duplicate relationship.';method='Applied saved terminal decisions after current-inventory reconciliation. No source finding was refetched. The lone saved approval received the current quality assessment required by AGENTS.md.';results=[ordered]@{saved_terminal_exclusions_reused=18;duplicate_relationship_retained=1;saved_approval_changed_to_excluded=1;linked_canonical_agenda_excluded=1};records=@($records);quality_reassessment=[ordered]@{id=$approved.id;prior_recommendation='approved for addition';current_decision='excluded';meeting_status='Agenda plus a procedural notice resolution; not minutes.';meeting_occurrence='Not inferred.';approved_minutes='Not needed for disposition because the record fails the prior standalone-substance and quality test.';stronger_record='No stronger meeting record is claimed; the decision does not depend on a missing-minutes conclusion.';canonical_page=$approved.proposed_canonical_page};duplicate_relationship=[ordered]@{duplicate_id='src-d5cfa0fec162e3c1';canonical_id='src-ff9893ec1cd700be';basis=$research.duplicate[0].basis};safeguards_observed=[ordered]@{r2_mutation=$false;public_content_changed=$false;merge_or_deploy=$false}}
$counts=[ordered]@{}; foreach($status in $inventory.allowed_statuses){$counts[$status]=@($inventory.candidates|Where-Object status -eq $status).Count}; $inventory.counts=[pscustomobject]$counts; $pending=@('pending review','approved for addition','downloaded','parsed','description drafted','placement assigned'); $eligible=@($inventory.candidates|Where-Object {$_.status -in $pending -or ($_.status -eq 'implemented' -and $_.validation_status -ne 'passed')}|ForEach-Object id|Sort-Object); $inventory.next_pending_id=if($eligible.Count){$eligible[0]}else{$null}; $inventory.generated_at=$now
Write-AtomicJson $inventory $InventoryPath; Write-AtomicJson $artifact $OutputPath; [pscustomobject]@{counts=$counts;next_pending_id=$inventory.next_pending_id;artifact=$OutputPath}|ConvertTo-Json -Depth 5
