"""Build explicit September 26 dispositions and separate owner/work queues."""
import collections,hashlib,json,re
from pathlib import Path

if __name__ == '__main__':
    from GovernedEntrypoint import require_tool_governance
    require_tool_governance(__file__)

ROOT=Path(__file__).resolve().parents[2];F=ROOT/'project-state/discovery/human-review-reassessment-2026-09-26'
def load(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def save(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
base={r['id']:r for r in load(F/'baseline-records.json')};q=load(F/'baseline-queue.json');ev={r['id']:r for r in load(F/'family-evidence.json')['records']};retrievals=load(F/'retrievals.json')['records']
updates=[];decisions=[];followups=[];owners=[]
def scope(row,reason,positive=True,geo=None,connection=None,value=None):
    return dict(assessed_at='2026-09-26',geographic_institutional_scope=geo or 'City of Albuquerque and its directly connected public infrastructure/services',specific_albuquerque_connection=connection or row['title']+' concerns the named Albuquerque public facility, network, land-use decision or expenditure described in the saved official source.',abqinfo_public_information_value=value or reason,general_context_exclusion_test='A source must provide material Albuquerque public-policy, infrastructure or government information; publisher jurisdiction, incidental references, generic templates and low-value operational fragments do not suffice.',final_scope_decision='passes_both_gates' if positive else 'excluded_insufficient_abqinfo_usefulness',substantive_rationale=reason)
def disposition(i,status,reason,**changes):
    row=base[i];changes=dict(changes,status=status,review_reason=None,exclusion_reason=reason if status in ['excluded','duplicate','superseded'] else None,validation_status='2026-09-26 policy reassessment: '+reason,processing_notes=row.get('processing_notes',[])+['Human-review reassessment 2026-09-26: '+reason+' Evidence: project-state/discovery/human-review-reassessment-2026-09-26/family-evidence.json and retrievals.json.'])
    updates.append(dict(id=i,changes=changes));decisions.append(dict(id=i,title=row['title'],status=status,rationale=reason,evidence_artifacts=ev[i]['evidence_artifacts'],retrieval_urls=[r['url'] for r in ev[i]['retrievals']],outcome_class='work_prerequisite' if status=='pending review' else 'automatic_disposition'))
def pending(i,reason,prerequisite):
    disposition(i,'pending review',reason)
    followups.append(dict(id=i,title=base[i]['title'],reason=reason,required_evidence=prerequisite,research_authorized=True,owner_decision_required=False,recovery_evidence='project-state/discovery/human-review-reassessment-2026-09-26/retrievals.json'))
def exclude(i,reason,geographic=False):
    a=scope(base[i],reason,False)
    if geographic:a.update(final_scope_decision='excluded_insufficient_albuquerque_relevance',geographic_institutional_scope='Regional or statewide material without a specific material Albuquerque component',specific_albuquerque_connection='No specific material Albuquerque component is established by the reviewed subject and saved official-source context.')
    disposition(i,'excluded',reason,scope_assessment=a)
def approve(i,reason,component=False,live=False,connection=None):
    row=base[i];good=[r for r in ev[i]['retrievals'] if r.get('page_count') and not r.get('truncated')]
    changes=dict(scope_assessment=scope(row,reason,connection=connection))
    if not live:
        assert good,i+' needs a verified complete static original'
        r=good[0];assert (ROOT/'tmp/pdfs/human-review'/f'{i}.png').exists(),'Visual review evidence missing '+i
        quality=dict(reviewed_document_content=True,visual_inspection_completed=True,standalone_public_value='medium' if component else 'high',information_density='visual_or_tabular' if r['word_count']<250 else 'substantial',series_relationship='component' if component else 'standalone',publication_form='consolidated_master' if component else 'standalone',rationale=reason+' The measured original is substantive and interpretable, and its named Albuquerque policy or capital information goes beyond generic administration or incidental context. No visible publication is approved by this background decision.',page_count=r['page_count'],extracted_word_count=r['word_count'],visual_inspection_evidence='tmp/pdfs/human-review/'+i+'.png')
        if component:quality['aggregation_rationale']='Retain the exact original and its distinct project or deliberative content within a complete chronological or program master. Shared family context supplies interpretation; a separate fragmentary public entry is not authorized.'
        if r['word_count']<250 and not component:quality['limited_content_exception']='This scanned legal instrument or dense visual table has material named Albuquerque policy or expenditure content. Low extractable text reflects visual/scanned information rather than a skeletal administrative request.'
        changes.update(local_path=r['saved_source'],size_bytes=r['size_bytes'],checksum_sha256=r['sha256'],quality_assessment=quality)
    disposition(i,'approved for addition',reason+' Inventory eligibility only; static archival/public-byte verification and future visible editorial approval remain prerequisites.',**changes)
def owner(package_id,title,ids,reason,question,options,review_reason):
    owners.append(dict(package_id=package_id,title=title,affected_record_ids=ids,decision_question=question,options=[dict(option=a,consequence=b) for a,b in options],decision_kind=review_reason,why_owner_judgment_required=reason))
    for i in ids:
        row=base[i];changes=dict(status='requires human review',review_reason=review_reason,validation_status='Genuine owner decision: '+reason,processing_notes=row.get('processing_notes',[])+['2026-09-26 reassessment: factual research and obsolete authorization gates are separated from the owner choice. '+reason])
        updates.append(dict(id=i,changes=changes));decisions.append(dict(id=i,title=row['title'],status='requires human review',outcome_class='owner_decision',rationale=reason))

owner('fiber-correspondence','Fiber hearing correspondence: privacy and presentation',['src-05b68a5758490499'],'The preserved correspondence contains resident communications and complaints. Choosing full originals, redaction or a summary determines privacy exposure and editorial presentation; source recovery cannot make that choice.','Retain full resident correspondence, authorize a redacted derivative/summary, or leave this material held?', [('Full original','Owner accepts the privacy exposure; any implementation follows a separate visible review stage.'),('Redacted derivative or summary','Authorize a separate redaction/editorial stage while preserving original provenance and distinguishing derivatives.'),('Keep held','Preserve the existing original and evidence without further archive or content action.')],'privacy_editorial_presentation')
owner('art-advocacy-primary-sources','ART advocacy records: contributed-source editorial policy',['src-671b4bd36e11e0d9','src-8903198f1d3c22e1','src-aab5517438784db7'],'These are identified advocacy/commentary and a participant meeting account, already preserved as contributed originals. Their nongovernment authorship is not disputed. The genuine choice is whether ABQInfo admits this attributed advocacy evidence, rather than representing it as an official government finding.','Admit these attributed contributed advocacy records within an ART historical evidence package, or exclude/hold them under the official-record editorial policy?', [('Attributed historical evidence','Owner permits nongovernment primary evidence with explicit authorship and viewpoint labels; no claim of official findings or approved minutes.'),('Exclude from public-facing package','Record an owner editorial exclusion; existing historical bytes are preserved and any visible removal needs manual review.'),('Keep held','No new visible action while editorial disposition remains open.')],'contributed_source_editorial_policy')
drafts=['src-10209c5fcdce2906','src-30b5123b798a30f3','src-3ff7d77c284d06a8','src-967a816e5ddac695','src-dda1163373f3754c','src-f904f6d8bf3787f5']
owner('dpm-historical-drafts','DPM historical proposals: retention and presentation',drafts,'Draft labels and Chapter 7 proposed status are established. No owner is asked to determine adoption. The editorial choice is whether substantive pre-adoption proposals belong in a clearly labeled historical proposal series alongside adopted standards, given the already preserved sibling draft.','Preserve these as explicitly historical proposals within a DPM series, or limit the public historical package to adopted standards and minutes?', [('Historical proposal series','Retain as proposals only, with draft dates and adopted-record relationships; never label them current or enacted.'),('Adopted records only','Apply an editorial exclusion of these proposals while preserving dated research and any existing original bytes.'),('Keep held','No new archives or content for this family pending owner editorial choice.')],'historical_draft_editorial_policy')
wire='src-333e4b4b3970edc1'
owner('wireless-checklist','Wireless review checklist: borderline public-information value',[wire],'The ten-page City checklist interprets a named Albuquerque zoning-code section but is also an internal applicant-routing form. Its substantive local regulatory content is credible; the usefulness of a separate retained record is genuinely close.','Does this code-interpreting staff checklist merit retention as a historical regulatory aid, or exclusion with routine application paperwork?', [('Exclude','Default: prefer final wireless regulations and application standards over an internal routing checklist.'),('Retain historical regulatory aid','Owner admits its distinct interpretation value; subsequent archival and visible editorial review remain required.')],'mission_scope_borderline')
updates[-1]['changes']['scope_assessment']=dict(assessed_at='2026-09-26',title=base[wire]['title'],publisher=base[wire]['agency'],date=base[wire].get('date') or 'May 2017',geographic_institutional_scope='City Albuquerque wireless telecommunications zoning administration',specific_albuquerque_connection='Interprets former Albuquerque Zoning Code section 14-16-3-17, effective December 22, 2014, for City wireless-facility review.',potential_abqinfo_public_information_value='Ten pages of code-specific criteria may explain historical wireless-facility regulation beyond the blank application form.',reason_does_not_confidently_pass='Staff routing, fill-in questions and procedural checks dominate parts of the record; final regulations may provide the same reader value more directly.',reason_does_not_clearly_fail='The checklist interprets a named local zoning section in substantive detail, rather than providing only generic or statewide paperwork.',proposed_page_or_section_if_admitted='Development process: historical wireless-facility standards',recommended_default_disposition='Exclude',final_scope_decision='requires_human_scope_review',substantive_rationale='Specific Albuquerque legal criteria and credible regulatory information coexist with internal applicant-processing content. Owner editorial significance judgment should determine retention; successful retrieval alone is insufficient.')

handled={x['id'] for x in updates}|{'src-4996854ae4e1a349','src-a738fd67bc6abac6','src-c7fcd58b9998999c'}
duplicate_map={'src-78f0a20b0c2e1298':'src-ff823647e5c83f56','src-db3d3c222ac1cf37':'src-b6907ea6557674ae','src-bedc45794b5b0841':'src-db8b649daf20497b'}
for i,can in duplicate_map.items():
    match=next(m for m in ev[i]['exact_hash_matches'] if m['id']==can);assert match['status']=='validated'
    disposition(i,'duplicate','The archived copy matches exact SHA-256 and size of the already validated authoritative canonical record '+can+'. Preserve the historical R2 key and source history; no additional archive or standalone entry is justified.',canonical_candidate_id=can)
    handled.add(i)
superseded={
 'src-0b1642254494f22e':('https://documents.cabq.gov/planning/UDD/CompPlan2017/SectorPlans/EastDowntownSDP-REPEALED.pdf','The complete enacted R-2005-032 regulatory package is recovered and reviewed. The isolated floor substitute lacks its adopted exhibits and is superseded for canonical historical use.'),
 'src-16da4791a0edb197':('https://legistar.granicus.com/cabq/attachments/9094.doc','Official action history identifies enacted O-2009-014, version 3, and the final O-35fsfinal attachment. The earlier floor-substitute delivery is not the canonical enacted version.'),
 'src-1288d4b8b7490606':('https://legistar.granicus.com/cabq/attachments/9637.doc','Official action history identifies enacted R-2010-005, version 2, and its R-1final attachment. Preserve the earlier bill as superseded rather than claiming it is the enacted original.'),
 'src-338b0d72594a0aad':('https://legistar.granicus.com/cabq/attachments/10291.doc','Official action history and final R-58fsfinal attachment establish R-2010-060. The held budget floor-substitute delivery is superseded for canonical legal presentation.'),
 'src-a9d18b1ea8963cad':('https://legistar.granicus.com/cabq/attachments/10291.doc','The held redline belongs to the same F/S R-10-58 proposal family, not a separate final instrument. The official enacted R-2010-060 budget and final attachment supersede the proposal/redline presentation.'),
 'src-3ce96f0fc670867e':('https://legistar.granicus.com/cabq/attachments/9ec881df-9da9-4966-b32a-5f9294e4e9ba.pdf','The recovered City action history identifies R-2024-018 as enacted and published, with an exact R-17Enacted attachment. The held approved floor substitute is superseded for final legal-record use.'),
 'src-77df51d4334f3749':('https://legistar.granicus.com/cabq/attachments/8696.pdf','O-08-58 was enacted as O-2009-009. Full word comparison shows the held 59-page file is the combined code, not only general Part A; the adopted combined attachment replaces every 04/02/09 Draft footer with Final. Preserve this mislabeled draft delivery as superseded.'),
 'src-05176d26d35effd3':('https://www.cabq.gov/council/documents/form-based-code/fbz_part_b.final.pdf','The official adopted FBZ link and O-2009-009 action history establish the final Part B. Full word comparison identifies only replacement of dated Draft footers by Final; the April 2 draft is superseded.'),
 'src-bdb71a8eaf8a29fa':('https://www.cabq.gov/council/documents/form-based-code/fbz_part_c.final.pdf','The official adopted FBZ link and O-2009-009 action history establish the final Part C. Full word comparison identifies only replacement of dated Draft footers by Final; the April 2 draft is superseded.')}
for i,(successor,reason) in superseded.items():
    disposition(i,'superseded',reason,cited_successors=list(dict.fromkeys(base[i].get('cited_successors',[])+[successor])));handled.add(i)
for i,bill in [('src-0feec7ebf6650e27','R-04-158'),('src-bc91d8e4f296d80b','O-23-96')]:
    exclude(i,'The exact official City Legistar status and complete action history record '+bill+' as Died on Expiration, with no enactment. This unadopted substitute is not a final regulatory record; default final-record policy excludes it without inferring enactment from postponements or the misleading passed-date field.');handled.add(i)

approved_static={
 'src-0d56a1f406d5c7fd':('The 2015 Metropolitan Redevelopment bond scopes identify $2.375 million and named Rail Yards, Downtown/Innovation District, East Gateway and West Central redevelopment work. The dense expenditure table has substantive public finance value within the complete bond-program family.',True),
 'src-0d81ec5c9bdeb726':('The March 1, 2005 Impact Fee Committee memorandum records distinct recommendations on Albuquerque police/fire, parks, open-space, roadway and drainage capital programs. It is substantive committee policy advice, explicitly distinguished from adopted legislation.',False),
 'src-0e84cb9afce66afc':('The October 5, 2004 committee report evaluates Albuquerque drainage impact-fee service areas, costs, methodology, financing and capital projects, with maps and tables. Its recommendation status is explicit, and the complete report explains a material City stormwater-finance decision.',False),
 'src-5de108fb850c221f':('The Senior Affairs scope contains distinct Bear Canyon and North Domingo Baca capital projects omitted from the current Community Facilities compilation. Preserve the exact dense table as a complementary 2009 program component; do not call it a duplicate or publish it independently.',True),
 'src-6fe3ca04cbe476d5':('The Senior Affairs bond summary provides year-by-year named City facility allocations and is complementary to its scope sheet. Exact family review confirms the omitted project rows; preserve within the complete capital-program master rather than as an isolated excerpt.',True),
 'src-d2d3b593d77a2885':('The Family and Community Services schedule contains distinct Holiday Park, Pat Hurley and Storehouse allocations missing from the canonical compilation. The previously duplicate twin shares exact bytes with this row; preserve the record as a complementary master component, without changing that unrelated twin in this task.',True),
 'src-5b9de5b2cda39393':('The complete 57-page official East Downtown/Huning Highland EDo package contains the adopted 2005 regulatory plan, subsequent signed amendment material and an explicit R-17-213 repeal watermark. It is a substantial historical Albuquerque land-use record, never current zoning guidance.',False),
 'src-100dcafff14a7b22':('The complete December 4 and 11, 2025 DPM minutes record City committee motions and amendments to local infrastructure, transportation and water-authority procedures. Preserve as a chronological governance-series component; the former frozen-batch restriction is obsolete.',True),
 'src-0d585b0b0e0819d7':('The approved October 18, 2022 Mid-Region Regional Transportation Plan contains substantive Albuquerque metropolitan network, safety, congestion and implementation actions. Regional scope alone is insufficient, but its measured local planning program and infrastructure maps establish material Albuquerque value.',False),
 'src-0e06267dc47f72c1':('The signed R-2017-030 package records the March 2017 North Fourth Street corridor moratorium, Council vote, Clerk memorandum and interim design requirements. Preserve as an expired historical transition instrument, never a current moratorium.',False),
 'src-0ee0b959ce0e2a95':('The 59-page official Trumbull compilation contains the neighborhood sector plan and signed 2003/2011 amendment material. Its historic land-use, redevelopment and zoning evidence is substantial; future presentation must explain supersession by later zoning rather than imply current force.',False)}
for i,(reason,component) in approved_static.items():approve(i,reason,component);handled.add(i)

county_exclusions={
 'src-1406b13347a41e49':'The Steve Schiff HVAC page describes equipment replacement and internal building maintenance. A local address and cost do not make this peripheral operating detail a substantive separate ABQInfo public-policy or infrastructure record.',
 'src-3b8da1ebd2bd4254':'Frost Road trail repaving is an East Mountain local project; County jurisdiction and its Albuquerque contractor do not establish a specific material Albuquerque component.',
 'src-733d883e1f0d1160':'Frost Road trail extension from Candy Court to Vallecitos is an East Mountain local trail project without a specific material Albuquerque component.',
 'src-f3b165a6cf65f33e':'The official page locates Fire Station 41 at 10838 Highway 337, Tijeras. County jurisdiction alone does not establish a material Albuquerque public-information component.',
 'src-df097f9ace534aba':'Public safety memorial dedication is commemorative event/facility material; the named Albuquerque park does not supply substantive policy, expenditure analysis or infrastructure planning value for a separate retained entry.',
 'src-ee461f91765ef06d':'The North Valley Library page is a restoration completion punch list of cleaning, locks, fencing and handover. Local facility relevance does not overcome its low independent public-policy information density.',
 'src-f22d856f3e6fc2b3':'Sunflower Meadow Park trail repaving and curb work is a skeletal maintenance schedule. It adds little substantive public-policy or infrastructure information beyond the originating agency notice.'}
for p in q['packages']:
    for r in p['records']:
        i=r['id'];row=base[i];pkg=p['package_id']
        if i in handled:continue
        if pkg=='bernco-project-attachments':
            exclude(i,'Recovered or context-verified project attachment: '+row['title']+'. This is a short-lived work-zone map, construction notice, door hanger, look-ahead or contractor schedule subordinate to the full official County project page. It does not independently explain an Albuquerque policy, adopted infrastructure design or durable capital-program decision; current policy excludes operational fragments rather than treating link failure as an owner gate.')
        elif pkg=='bernco-project-pages':
            if i in county_exclusions:exclude(i,county_exclusions[i],i in ['src-3b8da1ebd2bd4254','src-733d883e1f0d1160','src-f3b165a6cf65f33e'])
            elif i in ['src-143f58c34ccb049a','src-4d5d39b12d50677f','src-37fb581fedd3725f']:
                pending(i,'Source access or facility identity/location remains a Codex prerequisite, not an owner decision. The recovered Fire Station 46 page contains Station 41 text; Station 43 needs an exact local-service connection; Mountain View timed out.','Recover/reconcile the exact project page and facility identity/address, then apply both scope gates. Do not infer a geographic connection from County jurisdiction or a mismatched title.')
            else:
                raise ValueError(i+': shared County-project approval recipe retired by PR207 owner correction. Use a fresh governed, individual two-gate assessment with concrete durable public-information value; local official provenance and named capital work alone are insufficient. Historical September 26 decisions remain preserved, and this failure writes no new dispositions.')
        elif pkg=='nmdot-recovery-scope':
            exclude(i,'The exact NMDOT source context identifies '+row['title']+' as a statewide administrative form/contact/tool/guide, a telephone-link artifact, or a Santa Fe/southern-New-Mexico shuttle schedule. No specific material Albuquerque project, decision or service component is established. Statewide applicability and originating from a regional transit link do not pass the Albuquerque gate.',True)
        elif pkg=='bernco-standards-page':
            exclude(i,'The recovered landing page introduces the County technical standards and links their adopted complete standard and GSI appendix. It is a source-navigation/adoption-context wrapper to the complete standards already retained, not a distinct standard. Preserve its official URL as provenance; no separate public-facing record is justified.')
        elif pkg=='county-records-service':
            exclude(i,'The recovered County public-information request page is a procedural request gateway. County jurisdiction and possible use by an Albuquerque requester do not supply a distinct substantive Albuquerque policy or infrastructure record; transactional request instructions belong with the originating agency.')
        elif pkg=='ahymo-model':
            exclude(i,'The official City Hydrology page identifies AHYMO-S4-R2 as a hydrologic model software delivery. A generic computational utility is peripheral technical-operational material, not a substantive Albuquerque project study, drainage decision or adopted policy record; publisher jurisdiction does not establish independent ABQInfo value.')
        elif pkg=='regional-transit-recovery':
            if i=='src-105264c6cb316de5':approve(i,'The current official Downtown Albuquerque Rail Runner station page describes Alvarado Transportation Center connections, ABQ RIDE integration, accessibility, bicycle access and parking. It materially explains Albuquerque transit infrastructure and service use; retain as a live source with current details.',live=True,connection='Downtown Albuquerque Rail Runner station at 100 First Street SW, its Alvarado/ABQ RIDE transfer terminal and accessible intermodal facilities.')
            elif i=='src-0c53cff9813e08d6':exclude(i,'The recovered Downtown Bernalillo station-area vision concerns Camino del Pueblo, Bernalillo housing and local development. Rail Runner network membership and regional publisher jurisdiction do not establish a specific material Albuquerque component.',True)
            else:exclude(i,'This isolated transit FAQ/contact-directory entry, expired heat/event notice, or Santa Fe event-service link does not independently explain Albuquerque transit policy or durable infrastructure. Broader maintained service sources carry the useful context; the old failed-link gate is not an owner decision.')
        elif pkg=='frozen-editorial-src-0ce9e0677d08c174':approve(i,'The official City explainer distinguishes Albuquerque bicycle routes, boulevards, buffered/protected lanes, trails, sidepaths and crossing/detection treatments. This substantive local infrastructure information is eligible; the old frozen-batch restriction is obsolete.',live=True)
        elif pkg=='frozen-editorial-src-0d8b434458a51c1d':approve(i,'The official ABQ-PLAN entry point explains City land-use/zoning applications, permits, licensing, public record searches and status tracking. It is substantive Albuquerque development-service information, not an isolated transaction form.',live=True)
        elif pkg=='frozen-editorial-src-0e0cd2037365e977':approve(i,'The official Westside project overview documents McMahon bicycle lanes, Central trail segments and Coors landscaping/trail design with dated milestones. Named Albuquerque transportation projects establish substantive public infrastructure value; do not imply every old milestone is current.',live=True)
        elif pkg in ['frozen-editorial-src-0f5140179b1f087f','frozen-editorial-src-10972f1433d33ea3']:
            exclude(i,'The reviewed record is a launch/celebration announcement, rather than the final planning or police-reform outcome. Its local connection is clear but an isolated event notice adds insufficient substantive public-policy information for a separate retained entry; any final plan is a distinct research lead.')
        elif i=='src-a4e93912f58bcb5d':exclude(i,'The four-page Lewis budget wage-cut exhibit is a supporting proposal fragment within F/S R-10-58, with an exact duplicate delivery already identified. The final enacted R-2010-060 budget supplies the authoritative program context; the exhibit is not independently retained as a final policy instrument.')
        elif i in ['src-2a3f612f818af629','src-ae351fd152ae1c8e','src-1f0f860a2332e181']:
            exclude(i,'The saved title and official-source context identify a broadband enrollment flier, general events calendar, or sign-posting agreement transaction form. Local availability does not provide sufficient independent ABQInfo public-policy value; source failure or a newer form does not require an owner decision.')
        else:
            reason='Bounded source retrieval, saved research and exact inventory identity comparisons did not establish the remaining source/family/finality prerequisite. This is Codex research work, not an owner choice; no approval, supersession or legal outcome is inferred.'
            need='Recover an exact authoritative original or successor; compare source identity, complete family and substantive content before applying current scope/quality/finality rules.'
            if pkg in ['pgs-enactments','council-legal-versions']:
                reason='Official bill adoption is now documented where available, but the held blank-enactment/missing-exhibit delivery has not been proved to be the complete enacted text. Exact adopted-version comparison remains a source/finality prerequisite, not an owner decision.'
                need='Compare the final action version and complete adopted text/exhibits with the held original; preserve distinct versions and do not equate a bill-level enactment with this delivery.'
            if pkg in ['trails-pid-agendas','council-meeting-recovery'] or i in ['src-7e7af2af147d96d7','src-dc3a192d194d3d65']:
                reason='Agenda original recovered where available; exhaustive approved-minutes and cancellation/no-quorum verification is not yet established. The standing missing-minutes rule supplies the retention criterion without an owner policy decision.'
                need='Review exact official meeting index, complete document directory and subsequent minutes/agenda approvals; exclude cancelled/no-quorum meetings and agendas when approved minutes exist. Retain only with the explicit approved-minutes-not-located label after exhaustive evidence.'
            if pkg in ['central-station-drafts','contributed-bike-provenance','unreconciled-staging','art-supporting-records']:
                reason='Exact archived/local identity is preserved, but official-source origin or complete-family identity remains unproved after bounded recovery. A source-provenance fact cannot be established by an owner preference or an R2 HTTP success.'
                need='Locate the exact government/project original and compare full size/SHA-256; distinguish annotations, draft generations, wrapper pages and contributed advocacy. Missing EC-175 must remain distinct from the validated parking study.'
            pending(i,reason,need)
        handled.add(i)
assert handled==set(base),(set(base)-handled)
assert len({x['id'] for x in updates})==len(updates)==202
for x in load(F/'archive-decisions.json'):
    decisions.append(dict(id=x['id'],title=base[x['id']]['title'],status='placement assigned',outcome_class='automatic_disposition',rationale='Obsolete storage-only gate resolved; positive scope/quality, official original identity and full public GET verification passed.'))
save(F/'decisions.json',dict(baseline_record_count=205,records=sorted(decisions,key=lambda r:r['id']),approved_updates=updates))
save(F/'owner-packages.json',dict(packages=owners))
save(ROOT/'project-state/discovery/codex-human-review-followup-queue.json',dict(schema_version=1,artifact_type='codex_research_prerequisite_queue',population='Unfinished research/source/finality prerequisites separated from the former 205-record human queue; no owner decisions and no false terminal resolutions.',records=sorted(followups,key=lambda r:r['id']),record_count=len(followups)))
counts=collections.Counter(r['status'] for r in decisions);summary=dict(baseline_records=205,fully_dispositioned_automatically=205-len(followups)-sum(len(p['affected_record_ids']) for p in owners),research_prerequisites=len(followups),genuine_owner_records=sum(len(p['affected_record_ids']) for p in owners),owner_packages=len(owners),obsolete_human_gates_removed=205-sum(len(p['affected_record_ids']) for p in owners),final_status_counts=dict(counts),r2_added_bytes=381871978,r2_final_bytes=10670960837)
save(F/'summary.json',summary);print(json.dumps(summary))
