[CmdletBinding()]
param([string]$OutputPath = 'project-state/discovery/historical-transportation-review-27-decisions.json')

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$taskPage = 'content/transportation/transportation-plans.md'
$operationsPage = 'content/transportation/operations-data.md'
$studiesPage = 'content/transportation/roadway-projects/studies.md'
$taskSource = 'https://www.cabq.gov/council/projects/completed-projects/2008/21st-century-transportation-task-force'
$montanoSource = 'https://www.cabq.gov/council/projects/completed-projects/2005/montano-corridor-studies'
$decisions = [Collections.Generic.List[object]]::new()

function Add-Decision([string]$Id,[string]$Title,[string]$Date,[string]$Key,[string]$Page,[string]$Source,[string]$Description,[string[]]$Locations=@()) {
  $item = [ordered]@{id=$Id;title=$Title;date=$Date;r2_key=$Key;canonical_page=$Page;source_page=$Source;description=$Description;processing_notes=@('Original authoritative City or regional-government PDF preserved without modification.','Description reviewed against extracted text and representative visual inspection.')}
  if($Locations.Count){$item.implementation_locations=$Locations;$item.cross_listing_approved=$true}
  $decisions.Add([pscustomobject]$item)
}

Add-Decision 'src-04c1343bcd698b63' 'Planned Growth Strategy Transportation-System Cost Findings' '2008-01-23' 'transportation/transportation-plans/cabq-planned-growth-strategy-transportation-costs-excerpt-2008.pdf' $taskPage $taskSource 'Compares road, transit, public, private, and societal transportation costs under trend, balanced-growth, and downtown-focused land-use scenarios, preserving the fiscal evidence presented to Albuquerque''s 2008 transportation task force.'
Add-Decision 'src-5c59cfb9745f1508' 'Planned Growth Strategy Policy, Regulatory, and Plan Review' '2008-01-23' 'transportation/transportation-plans/cabq-planned-growth-strategy-policy-regulatory-excerpt-2008.pdf' $taskPage $taskSource 'Reviews the Albuquerque and Bernalillo County policies shaping compact growth, centers and corridors, infrastructure timing, annexation, impact fees, transit-supportive development, and coordination between land-use and transportation investment.'
Add-Decision 'src-74c6250763ee3c21' 'City Capital Improvements Ordinance — 2008 Task Force Reference' '2008-01-23' 'transportation/transportation-plans/cabq-capital-improvements-ordinance-task-force-reference-2008.pdf' $taskPage $taskSource 'Preserves the capital-program rules reviewed by the task force, including maintenance priorities, ten-year programming, project evaluation, trails and bikeways funding, public reporting, and metropolitan transportation-plan coordination.'
Add-Decision 'src-d45aecabefa6c217' '2009 Capital Improvements Plan Priorities and Scoring Resolution' '2007' 'transportation/transportation-plans/cabq-2009-capital-plan-priorities-resolution-r-07-12.pdf' $taskPage $taskSource 'Documents proposed criteria, weights, policy priorities, and funding allocations for Albuquerque''s 2009 general-obligation bond program, connecting capital-project selection with infrastructure condition, adopted plans, public safety, growth, and neighborhood needs.'
Add-Decision 'src-2e670a3b5593ee35' 'MRCOG Regional Transportation Planning Briefing' '2008-02-05' 'transportation/transportation-plans/mrcog-regional-transportation-task-force-briefing-2008.pdf' $taskPage $taskSource 'Explains MRCOG''s metropolitan planning role, the 2030 MTP and TIP, Rail Runner and Rio Metro responsibilities, forecast growth, congestion, river crossings, multimodal needs, regional projects, and limited transportation funding.'
Add-Decision 'src-bdc584620c51dfa1' 'Albuquerque Metropolitan Area Intelligent Transportation Systems Briefing' '2008-04-01' 'transportation/operations-data/mrcog-albuquerque-its-task-force-briefing-2008.pdf' $operationsPage $taskSource 'Preserves the regional ITS framework presented in 2008, covering traffic-management, transit-security, dispatch, freeway systems, traveler information, communications, incident response, project programming, agency coordination, and the planned Regional Transportation Management Center.' @($operationsPage,$taskPage)
Add-Decision 'src-25c15ede0314ba7a' 'Street Maintenance and Rehabilitation in the Twenty-First Century' '2008-06-11' 'transportation/operations-data/cabq-street-maintenance-rehabilitation-task-force-briefing-2008.pdf' $operationsPage $taskSource 'Documents Albuquerque''s quarter-cent-tax street program, lane miles maintained, pavement-condition changes, bicycle-trail and sidewalk work, historic funding, projected needs, and the consequences of continuing or ending dedicated transportation revenue.' @($operationsPage,$taskPage)
Add-Decision 'src-5c9ad39184c0e9c3' '21st Century Transportation Task Force Enabling Ordinance O-07-71' '2007' 'transportation/transportation-plans/cabq-transportation-task-force-enabling-ordinance-o-07-71-2007.pdf' $taskPage $taskSource 'Creates the transportation task force and commissions the streetcar cost-benefit analysis, defining a citywide multimodal scope spanning roadway, transit, bicycle, pedestrian, paratransit, land-use, economic-development, funding, and tax-policy questions.'

Add-Decision 'src-26532dcb33a27b7d' 'Montaño Road Corridor Study — Wilson & Company' '2005-10-14' 'transportation/roadway-projects/studies/cabq-montano-road-corridor-wilson-study-2005.pdf' $studiesPage $montanoSource 'Evaluates Montaño Road from Coors Boulevard to Second Street using traffic modeling, public input, safety, noise, vibration, biology, lane alternatives, costs, and intersection operations, recommending four general-purpose lanes.'
Add-Decision 'src-f93f8f11481c3c74' 'Montaño Citizens Advisory Committee Recommendations' '2005-11-10' 'transportation/roadway-projects/studies/cabq-montano-citizens-advisory-committee-recommendations-2005.pdf' $studiesPage $montanoSource 'Recommends general-purpose and HOV lanes, lower speeds, enforcement, redesigned intersections, roundabouts, protected walking and bicycling crossings, retained bike lanes, rapid bus service, commuter rail access, and intelligent transportation systems.'
Add-Decision 'src-17d49e3ef030ed1a' 'Montaño and Fourth Street Study Authorization — Resolution R-05-216' '2005-02' 'transportation/roadway-projects/studies/cabq-montano-study-authorization-resolution-r-05-216-2005.pdf' $studiesPage $montanoSource 'Authorizes and funds the Montaño and Fourth Street feasibility study, requiring public involvement, alternatives and financial analysis, HOV and bus-lane evaluation, agency collaboration, and coordination with surrounding corridor plans.'
Add-Decision 'src-203fb37e4964e658' 'Montaño Four-Lane Policy — Resolution R-04-204' '2005-05' 'transportation/roadway-projects/studies/cabq-montano-four-lane-policy-resolution-r-04-204-2005.pdf' $studiesPage $montanoSource 'Requests use of the bridge and corridor''s four-lane capacity while requiring North Fourth Street planning, Near North Valley planning, Montaño/Fourth intersection analysis, multimodal consideration, financial analysis, and recurring progress reports.'
Add-Decision 'src-922fcd8ff3e7ab91' 'Montaño HOV and River-Crossing Policy — Resolution R-05-382' '2005' 'transportation/roadway-projects/studies/cabq-montano-hov-river-crossing-policy-resolution-r-05-382-2005.pdf' $studiesPage $montanoSource 'Records the proposed City policy favoring two unrestricted lanes and a reversible HOV/transit lane, interim HOV striping, and compliance with regional planning, federal permits, historic-preservation requirements, and court decisions.'
Add-Decision 'src-1a82c77452c85991' 'Montaño Four General-Purpose Lanes Proposal — Resolution R-05-390' '2005' 'transportation/roadway-projects/studies/cabq-montano-four-general-purpose-lanes-resolution-r-05-390-2005.pdf' $studiesPage $montanoSource 'Records the competing proposal to operate Montaño between Coors and Fourth Street with four general-purpose lanes, citing the Wilson study, corridor capacity, safety analysis, environmental findings, and prior Council policy.'

foreach($d in $decisions){$words=@($d.description -split "\s+"|Where-Object{$_}).Count;if($words -lt 20 -or $words -gt 50){throw "$($d.id): $words words"}}
[ordered]@{schema_version=1;batch_id="historical-transportation-review-27";decisions=@($decisions)}|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $OutputPath -Encoding utf8
[pscustomobject]@{Decisions=$decisions.Count;OutputPath=$OutputPath}|ConvertTo-Json -Compress
