"""Explicit current-evidence outcomes; unresolved facts are never owner choices."""
from BackgroundFollowup import ROOT,F,load,save
base={r['id']:r for r in load(F/'baseline-records.json')}
retrievals=load(F/'retrievals.json')['records']
updates=[];decisions={}
def scope(r,reason,positive=True,connection=None,geography=None):
 return dict(assessed_at='2026-09-26',geographic_institutional_scope=geography or 'City of Albuquerque public services, capital planning and development regulation',specific_albuquerque_connection=connection or r['title']+' directly documents the named Albuquerque public subject.',abqinfo_public_information_value=reason,general_context_exclusion_test='Publisher jurisdiction, incidental geography, generic process diagrams and source-navigation wrappers cannot establish eligibility. Retention must materially explain a named Albuquerque policy, service, regulation or expenditure.',final_scope_decision='passes_both_gates' if positive else 'excluded_insufficient_abqinfo_usefulness',substantive_rationale=reason)
def change(i,status,reason,**fields):
 r=base[i];fields.update(status=status,review_reason=None,validation_status='Background follow-up 2026-09-26: '+reason,processing_notes=r['processing_notes']+['Background follow-up 2026-09-26: '+reason+' Evidence: '+F.relative_to(ROOT).as_posix()+'/retrievals.json and decisions.json.'])
 if status=='excluded':
  assessment=scope(r,reason,False)
  if i in ['src-4d5d39b12d50677f','src-37fb581fedd3725f','src-56784d45754c69cf','src-bbe0deabbd2d58fc']:
   assessment.update(geographic_institutional_scope='Tijeras and Sandia Park facilities/projects in the Bernalillo County East Mountains',specific_albuquerque_connection='No specific material Albuquerque component is established. County jurisdiction and regional context are insufficient.',final_scope_decision='excluded_insufficient_albuquerque_relevance')
  fields.update(exclusion_reason=reason,scope_assessment=assessment)
 updates.append(dict(id=i,changes=fields));decisions[i]=dict(id=i,title=r['title'],outcome=status,rationale=reason,evidence_artifact=F.relative_to(ROOT).as_posix()+'/retrievals.json')
def approve(i,reason,component=False,scanned_words=None,**fields):
 r=base[i];x=next(x for x in retrievals if x.get('id')==i and x.get('page_count') and not x.get('truncated'))
 if r.get('checksum_sha256'):assert r['checksum_sha256']==x['sha256'] and r['size_bytes']==x['size_bytes']
 quality=dict(reviewed_document_content=True,visual_inspection_completed=True,standalone_public_value='medium' if component else 'high',information_density='visual_or_tabular' if x['word_count']<250 else 'substantial',series_relationship='component' if component else 'standalone',publication_form='consolidated_master' if component else 'standalone',page_count=x['page_count'],extracted_word_count=x['word_count'],rationale=reason,visual_inspection_evidence='tmp/pdfs/background-followup/'+i+('-sheet.png' if i in ['src-06d0fc4cd0abdef6','src-070a763aa9701f86','src-51fb6dc80b316253'] else '-fresh-1.png'))
 if component:quality['aggregation_rationale']='Preserve the exact original within its named capital or Council-oversight family; no separate fragmentary visitor entry is authorized.'
 if x['word_count']<250:quality['limited_content_exception']='The rendered original contains '+('a dense dated deployment table with 172 total assignments; extraction has no text and the unexplained column abbreviations must remain explicit limitations' if i=='src-51fb6dc80b316253' else 'a City Engineer jurisdiction memorandum with five concrete infrastructure-review triggers; extraction has no text because the original is scanned')+'. Its distinct regulatory or oversight value is established by the complete visual record, not its text count.'
 fields.update(local_path=x['saved_source'],checksum_sha256=x['sha256'],size_bytes=x['size_bytes'],scope_assessment=scope(r,reason),quality_assessment=quality)
 change(i,'approved for addition',reason+' Inventory/archive stage only; canonical-page editorial work remains separate.',**fields)

approve('src-10c3dec88d8336ea','The July 8, 2019 City Engineer memorandum defines five specific DRC plan-review and City Work Order triggers for public infrastructure, including DRB infrastructure lists, curb/pavement alignment, water-line thresholds, sewer work and complex hydrology/transportation work. Fresh exact official bytes and the complete rendered memorandum resolve source identity. It is a concrete historical Albuquerque development-regulatory reference, not a blank routing form.',date='2019-07-08')
approve('src-5cea73d2df70dabb','The complete two-page DMD/Streets 2009 GO Bond Summary gives project-by-project amounts for the 2009, 2011, 2013, 2015 and 2017 program cycles, including Lead/Coal reconstruction, bridges, trails, arterial widening and traffic improvements. Both pages were reviewed alongside the saved complete 2009 capital family and the newly archived Senior Affairs/Family and Community Services summaries. Fresh exact official bytes resolve the remaining identity issue; retain within a capital-program master, never imply all projected cycles were actual expenditures.',component=True,title='2009 GO Bond Program: DMD Streets Summary, 2009–2017')
change('src-143f58c34ccb049a','approved for addition','The recovered exact County project page establishes Mountain View Phase 1A drainage improvements between Rio Bravo, South Diversion Channel and the Barr Main Canal, including the downstream pond east of Second Street, WSP design and state-capital-outlay funding. This is a material Albuquerque/South Valley drainage-network project with durable design and funding context. It is a live project page, not a static original; dated construction forecasts do not establish current completion.',scope_assessment=scope(base['src-143f58c34ccb049a'],'Explains the named Mountain View drainage system, phase boundaries and public funding.',connection='Mountain View drainage project in the Albuquerque South Valley, south of Rio Bravo and east of Second Street.'))
approve('src-06d0fc4cd0abdef6','The previously approved fifteen-page 2026 mayoral address has fresh exact official-source bytes and complete rendered-page review. It states the Albuquerque administration policy framework for housing, public safety, family services and use of municipal land and facilities. Preserve as a dated attributed mayoral address, not an adopted Council policy. The earlier architecture hold concerns future public placement and does not prevent this explicitly authorized original archive.')
approve('src-070a763aa9701f86','The exact official one-page Council oversight response contains 312 words explaining the Early Head Start grant governance advisory committee, its 2022 archival, and the January/February 2025 reinstatement process. The PDF explicitly identifies EHS as Early Head Start; the old Environmental Health Services expansion was incorrect. Preserve the administration position without independently deciding legal compliance. Future editorial placement remains unresolved.',title='Administration responses to Councillor Grout on Early Head Start governance',description="The Administration's written answers to a councillor's questions about the Early Head Start governance advisory committee, its archived status, and steps toward reinstatement. Records the Administration's position without independently determining legal compliance.")
approve('src-51fb6dc80b316253','The previously approved exact official Council-response original is a scanned table of National Guard deployment assignments dated June 8–24, 2025, totaling 172 across BCSO, FH, NE, NW, SE, SW, UNI and VA columns. The complete rendered table is legible, but its column abbreviations have no legend and the counts must not be represented as unique personnel. Retain as a component of the attributed Council oversight response, not a context-free standalone entry; architecture remains unresolved.',component=True,description='Preserves the Administration-supplied National Guard deployment table for June 8–24, 2025, with 172 total assignments across the printed columns. The original provides no abbreviation legend; totals should not be read as unique personnel counts.')

for i,reason in {
 'src-0eb2bcba2848b4dd':'The held exact 196-word, one-page Bernalillo County Transportation Planning Process diagram is a generic CIP/ICIP/TIP/STIP funding and procedural flowchart. It contains no named Albuquerque project, specific City decision or substantive local program analysis. Complete original review supplies a definitive scope exclusion independent of the still-missing former URL; County jurisdiction alone cannot pass either gate.',
 'src-19d8cdfc785b762e':'The canonical Legistar View delivery recovered from this misleading Minutes link is a nine-page President Letter of Introduction, revised August 4, 2026. It lists communications and referral/introductory routing, not approved meeting minutes or the substantive attached records. Exclude this administrative delivery and preserve the identity correction; infer no meeting or legal outcome.',
 'src-22d52189423d05f0':'The canonical Legistar delivery is an accessible agenda representation. It is a delivery/navigation alternative to the meeting agenda, not a distinct adopted decision or approved minutes record. No standalone archive/public entry is warranted for this accessible wrapper.',
 'src-268512229a0c3550':'The nested resolveuid URL recovers to exactly the same canonical accessible-agenda URL and bytes as src-22d52189423d05f0. Both are excluded accessible delivery wrappers; no source or approved-minutes identity is inferred.',
 'src-2454af27ff4945bf':'The canonical Legistar source is a City Council agenda, with referrals and links to separate attachments rather than the substantive documents. This routing index adds no distinct static public-information record beyond the maintained official meeting system. It is excluded on independent value, without asserting missing minutes or cancellation.',
 'src-2a8c47dfb71fe9f8':'The malformed City URL recovers to the official Legistar Intergovernmental Legislative Relations Committee department directory. It is a meeting/roster navigation page rather than a distinct policy or meeting record. Preserve canonical navigation in evidence; no separate static inventory entry is justified.',
 'src-2e234e9b6d4a2a8a':'The nested malformed City URL recovers to the official Legistar City Council department directory. This is a navigation wrapper to the Council meeting and legislation system, not a standalone document. No visitor-visible link change is made.',
 'src-319c77f6729ac516':'The broken nested public library path is a generic navigation artifact; the current official library homepage at abqlibrary.org is reachable. This row contains no named library plan, spending decision or historical service analysis to archive separately.',
 'src-4d5d39b12d50677f':'The exact County page explicitly locates Fire Station 46 at 25 Frost Road, Sandia Park. Its scope paragraph incorrectly refers to Station 41, but either named facility is an East Mountain facility and this page establishes no material Albuquerque component. The error is preserved, not silently repaired; County jurisdiction and mutual service context do not establish mission scope.',
 'src-37fb581fedd3725f':'The exact County page describes bedrooms, kitchen, roof and equipment-system remodeling for Fire Station 43. The official County District 5 GIS map places Station 43 in the East Mountains near Tijeras, outside Albuquerque. No specific material Albuquerque project or policy component exists; general County fire jurisdiction is insufficient.',
 'src-56784d45754c69cf':'The recovered official 111-page environmental evaluation concerns proposed development of the Luna Properties in Tijeras, as the exact County parent page explicitly states. The full scanned source and geographical project context do not establish a specific material Albuquerque component. Do not elevate County jurisdiction or regional environmental context into eligibility.',
 'src-bbe0deabbd2d58fc':'The exact County project landing page explicitly identifies the Luna Properties environmental evaluation as a Tijeras project and links the reviewed draft original. It establishes no specific material Albuquerque component and is independently excluded; no draft-finality inference is needed.'
}.items():change(i,'excluded',reason)

# Old Town edition comparison is separately proved over all five rendered pages.
comparison=F/'oldtown-edition-comparison.json'
if comparison.exists() and load(comparison)['equivalent_content']:
 change('src-0edd7472218d6529','excluded','The exact official Topic 1 tone edition contains the same 25 questions, 33-participant chart results and five-page layout as the color edition already validated at src-4f28a655d98c8ae3. Full-page visual/text comparison of both fresh official originals establishes a redundant presentation edition, not a new survey. It is not labeled byte-identical; the two different hashes and original provenance are preserved.')

specific={
 'lin-2f6fbe4ffb0b6564':'The current official Bike Gap Closure search returns zero records. The 2024 plan citation describes a program and associated project profiles; an exact official report/profile set must still be recovered and bounded before disposition.',
 'lin-7bdbcdc09efe2035':'The current official San Antonio Arroyo search yields no exact corridor plan. The plan citation is not an original; recover the complete adopted corridor plan and verify its exact version.',
 'src-0a69860a80fbe98a':'The live Girard Streetscaping page is reachable but no longer links the annotated 2022 PDF, and the held local path is absent. Recover the exact 17014412-byte, 22b6366d original or a proved official wrapper relationship; newer construction descriptions are not provenance for the old annotations.',
 'src-158f843cc102a40f':'The current Planning index still mislabels a HuningCastleRaynoldsSDP_2002 URL as Volcano Park; that PDF returns 404. Exact title/source reconciliation remains necessary; the wrong link cannot establish a Volcano Park original.',
 'src-352d880cb11386d3':'The current official Progress Report hub still links the 2004 report at the recorded 404 URL. No complete government-hosted 2004 original was recovered; the hub is not a replacement for the missing report.',
 'src-395957636cb2fed0':'The complete public 1993-plan original was recovered at its saved 4624017-byte R2 key. The recorded authoritative URL is an unavailable 2024 update summary, not the 1993 original. Recover the exact official 1993 delivery and establish historical version identity; public R2 success alone is insufficient.',
 'src-907f4de342216f97':'The complete current official 2024 plan is 513 pages / 68233939 bytes and differs from the held 144-page / 19715991-byte original on 31 extracted-text pages as well as missing appendices. Current Planning OnBase and cabq PDF deliveries match each other. Do not replace the held hash or infer complete adopted equivalence; recover the held exact edition or resolve all substantive version differences.',
 'src-a59d0a45be606c45':'The recorded OnBase ID currently delivers a two-page DMD letter, 338388 bytes / fa9ca0ae..., not the saved 2531246-byte Buena Vista roll plot. The held path is absent. Recover the exact roll-plot delivery from the official project system; do not overwrite historical identity with this unrelated letter.',
 'src-a614f077ace20401':'The complete public original is the recorded 131-page 2014 pre-adoption draft. Its exact official former delivery remains unrecovered; the 2015 final is a distinct 312-page document. Verify provenance and complete draft/final changes before any retention/supersession disposition.',
 'src-e80e0b49a4723c9a':'The linked current official Scale of the Prize report is 41 pages / 2724654 bytes and marked Draft Not For Release; the held original is 42 pages / 2766304 bytes. Resolve the additional page and substantive differences against the entire official report before claiming exact provenance or finality.',
 'src-e88f5a097091c5db':'The complete held one-page ART building-permits map has its saved exact hash, but current official ART/Building Permits searches do not recover that dated 2022–2023 original. GIS branding and open current data do not establish the exact historical export provenance.',
 'src-ea9839282b301e5f':'The saved 9388020-byte EC-175 original has no source URL and remains absent at its held path. Recover exact bytes and historical attachment identity; it must remain distinct from the already validated 2025 Downtown Parking Study.',
}
for i in load(F/'authorization.json')['followup_ids']:
 if i in decisions:continue
 r=base[i]
 if 'Station-Area Planning Draft' in r['title'] or i=='src-e0748ccf7ebc1a77':
  reason='The exact local original is preserved and measured. Current official title/chapter searches did not recover the government/project original for the complete September 2017 Central Avenue station-area collection. City branding, coherent draft pagination and R2 identity do not independently establish official provenance; recover the exact official complete family and distinguish component originals from later plans.'
 elif i in ['src-f7c7bd5b273def22','src-68582bc4fe41fb4f','src-fcbe6a7ebcf916a1','src-4cb190564a688d42','src-0f4496e4073a5e06']:
  reason='Current Legistar action histories and complete final-file attachments establish bill-level enactment, not that the held blank-enactment, floor-amendment or exhibit-incomplete PDF is the complete adopted delivery. Full Word/PDF comparisons and distinct page counts are saved. Resolve final action version, amendments and all referenced exhibits; do not infer missing legal text from adoption metadata. Erroneous /texts/{version} API responses have mismatched MatterTextMatterId and are rejected as evidence.'
 elif 'Agenda' in r['title'] or 'agenda' in r['title'] or i=='src-9dbe491dce873f71':
  reason='Exact agenda original recovered and measured; official meeting index/search and subsequent published agenda/minutes records reviewed. No complete approved-minutes and cancellation/no-quorum proof was established for this exact meeting. References to approving earlier minutes show minutes may exist but do not supply them. Retain the concrete prerequisite; no agenda archive or missing-minutes label is authorized until exhaustive official records and meeting-occurrence evidence resolve it.'
 else:reason=specific.get(i,'Exact original or full-family/version identity remains unproved by the saved current official retrievals; recover the specific authoritative original and compare complete source content before disposition.')
 if i in specific:reason=specific[i]
 decisions[i]=dict(id=i,title=r['title'],outcome='unresolved_evidence_prerequisite',rationale=reason,evidence_artifact=F.relative_to(ROOT).as_posix()+'/retrievals.json',required_evidence=reason,owner_decision_required=False)
save(F/'decision-updates.json',updates)
save(F/'decisions.json',dict(records=list(decisions.values()),followup_baseline_count=55,owner_packages_unchanged=True))
print('Explicit updates:',len(updates),'unresolved:',sum(r['outcome']=='unresolved_evidence_prerequisite' for r in decisions.values()))
