"""Regenerate current queue coverage and persist the owner decision handoff."""
from OwnerDecisions import *
import collections
inv=load(ROOT/'project-state/master-inventory.json');rows={r['id']:r for r in inv['candidates']};a=load(F/'authorization.json');receipts=load(F/'archive-receipts.json');live=load(F/'r2-final.json');old=load(F/'r2-baseline.json')
work=load(F/'baseline-followup-queue.json');work['records']=[r for r in work['records'] if rows[r['id']]['status']=='pending review'];work['record_count']=len(work['records']);assert work['record_count']==39;save(ROOT/'project-state/discovery/codex-human-review-followup-queue.json',work)
q=load(ROOT/load(ROOT/'project-state/ordinary-queue-current.json')['artifact']);q['pending_ids']=sorted(i for i,r in rows.items() if r['status']=='pending review');q['pending_review_count']=len(q['pending_ids']);q['newly_approved_backlog']=[r for r in q['newly_approved_backlog'] if rows[r['id']]['status']=='approved for addition'];save(F/'next-ordinary-queue.json',q);save(ROOT/'project-state/ordinary-queue-current.json',dict(schema_version=1,artifact=(F/'next-ordinary-queue.json').relative_to(ROOT).as_posix(),task=TASK))
summary=dict(task=TASK,state='archives_complete_validation_pending',owner_packages_resolved=4,owner_records_resolved=11,retained_records=9,excluded_records=2,unresolved_owner_packages=0,unresolved_owner_records=0,codex_followups=39,new_archives=len(receipts),added_r2_bytes=live['total_bytes']-old['total_bytes'],r2_objects=live['object_count'],r2_bytes=live['total_bytes'],remaining_storage_bytes=13000000000-live['total_bytes'],visitor_visible_changes=False,dispositions={i:rows[i]['status'] for i in a['allowed_ids']})
save(F/'summary.json',summary);a['state']=summary['state'];save(F/'authorization.json',a)
cp=load(ROOT/'project-state/checkpoint.json');cp.update(recorded_at=inv['generated_at'],counts_by_status=inv['counts'],next_pending_id=inv['next_pending_id'],remaining_nonterminal=sum(r['status'] in ['pending review','approved for addition','downloaded','parsed','description drafted','placement assigned'] or r['status']=='implemented' and r.get('validation_status')!='passed' for r in rows.values()),completed_item_range='All four owner packages resolved: nine historical originals retained, fiber correspondence and wireless checklist excluded; six new exact archives',resume_command='Read CURRENT.md and owner-decisions-2026-09-26 summary/authorization/validation/integration; do not repeat resolved owner decisions or uploads. The 39 Codex factual prerequisites remain unresolved.');cp['owner_decisions']=dict(artifact=(F/'summary.json').relative_to(ROOT).as_posix(),**summary);save(ROOT/'project-state/checkpoint.json',cp)
# Keep the resolved scope history in the exclusive queue.
scope=load(ROOT/'project-state/discovery/mission-scope-borderline-human-review-queue.json')
if not any(r.get('id')=='src-333e4b4b3970edc1' for r in scope['resolved_records']):scope['resolved_records'].append(dict(id='src-333e4b4b3970edc1',resolved_at='2026-09-26',disposition='excluded',reason='Explicit owner exclusion',authority_artifact=(F/'authorization.json').relative_to(ROOT).as_posix()));save(ROOT/'project-state/discovery/mission-scope-borderline-human-review-queue.json',scope)
current=f"""# ABQInfo Current Work

All four owner human-review packages are resolved by explicit September 26 decisions. All three ART advocacy originals are retained as attributed historical evidence, with authorship/viewpoint labels and no claim of official City findings or approved minutes. All six DPM originals are retained as a historical proposal/draft series with dates and adopted-record relationships preserved; they are never current or enacted standards. Fiber correspondence is excluded from the public collection: no original, derivative or summary publication. The wireless checklist is excluded. Research and provenance evidence remain preserved.

The authoritative inventory and owner/mission-scope queues now contain zero unresolved human-review records. The Codex follow-up queue remains 39 factual prerequisites; none was converted to an owner decision or inferred resolved. The ordinary queue remains 372 pending records, with the existing unrelated gates and source/family prerequisites preserved. Current pointer: `{(F/'next-ordinary-queue.json').relative_to(ROOT).as_posix()}`.

Six unchanged DPM originals were uploaded to absent keys and each complete public GET matched exact size and SHA-256: {summary['added_r2_bytes']} added bytes. Three ART originals were already archived and were not uploaded again. R2 is {live['object_count']} objects / {live['total_bytes']} bytes, leaving {summary['remaining_storage_bytes']} bytes below the 13000000000-byte ceiling. No deletion or overwrite. The historical 10-page BMP draft keeps its original hash; a later different 11-page source remains separate evidence. All six new objects are below 150000000 bytes. The unrelated 280024902-byte Sunport hold remains unchanged.

Decisions, immutable population, inspection measurements, archive intents/receipts, storage accounting and validation are saved in `{F.relative_to(ROOT).as_posix()}/`. Full validation and background-only integration/reconciliation remain pending. No `content/`, layouts, assets, static resources or visitor-visible configuration changed. Visible editorial implementation remains a separate manual-review stage. Further ordinary work requires the exact remaining factual evidence.
"""
(ROOT/'project-state/CURRENT.md').write_text(current,encoding='utf-8')
print(json.dumps(summary))
