"""Recompute exact queue coverage and persist the owner-authorized handoff."""
import collections,gzip,hashlib
from BackgroundFollowup import ROOT,F,load,save
inv=load(ROOT/'project-state/master-inventory.json');rows={r['id']:r for r in inv['candidates']}
a=load(F/'authorization.json');decisions=load(F/'decisions.json')['records'];byid={r['id']:r for r in decisions}
old=load(F/'baseline-followup-queue.json')
remaining=[]
for r in old['records']:
 d=byid[r['id']]
 if rows[r['id']]['status']=='pending review':
  assert d['outcome']=='unresolved_evidence_prerequisite'
  r.update(reason=d['rationale'],required_evidence=d['required_evidence'],recovery_evidence=d['evidence_artifact']);remaining.append(r)
save(ROOT/'project-state/discovery/codex-human-review-followup-queue.json',dict(schema_version=1,artifact_type='codex_factual_followup_queue',recorded_at='2026-09-26',baseline_count=55,record_count=len(remaining),resolved_count=55-len(remaining),research_authorized=True,owner_decision_required=False,task_artifact=F.relative_to(ROOT).as_posix()+'/decisions.json',records=remaining))
priorpointer=load(ROOT/'project-state/ordinary-queue-current.json');q=load(ROOT/priorpointer['artifact'])
q['pending_ids']=sorted(i for i,r in rows.items() if r['status']=='pending review');q['pending_review_count']=len(q['pending_ids'])
q['source_or_structural_blocked_pending_ids']={i:r for i,r in q['source_or_structural_blocked_pending_ids'].items() if i in q['pending_ids']}
q['source_or_structural_blocked_pending_ids'].update({r['id']:r['required_evidence'] for r in remaining});q['source_or_structural_blocked_pending_count']=len(q['source_or_structural_blocked_pending_ids'])
q['newly_approved_backlog']=[dict(id=r['id'],title=r['title'],status=r['status'],prepared=False,reason='Live maintained source; no static original to archive. Separate editorial approval remains required.' if not r.get('size_bytes') else 'Original exceeds 150000000-byte authorization; retain exact source and size hold.') for r in rows.values() if r['status']=='approved for addition']
q.update(actionability_basis='All 55 authorized follow-ups received current evidence review: 16 deterministic dispositions, 39 specific unresolved prerequisites. No owner choices or uncertain legal/minutes outcomes were inferred. Existing unrelated gates/live-service prerequisites remain unchanged.',followup_artifact=F.relative_to(ROOT).as_posix()+'/decisions.json',research_prerequisite_artifact='project-state/discovery/codex-human-review-followup-queue.json')
save(F/'next-ordinary-queue.json',q);save(ROOT/'project-state/ordinary-queue-current.json',dict(schema_version=1,artifact=(F/'next-ordinary-queue.json').relative_to(ROOT).as_posix(),task=F.name))
receipts=load(F/'archive-receipts.json');live=load(F/'r2-final.json');baseline=load(F/'r2-baseline.json')
summary=dict(task=F.name,baseline_followups=55,resolved_followups=55-len(remaining),unresolved_followups=len(remaining),followup_dispositions=dict(collections.Counter(rows[i]['status'] for i in a['followup_ids'])),owner_packages=4,owner_records=11,owner_choices_applied=0,exact_archives=len(receipts),r2_added_bytes=live['total_bytes']-baseline['total_bytes'],r2_final_bytes=live['total_bytes'],r2_final_objects=live['object_count'],storage_remaining_bytes=13000000000-live['total_bytes'],approved_live_pages=sum(r['status']=='approved for addition' and not r.get('size_bytes') for r in rows.values()),oversize_originals=[dict(id=r['id'],title=r['title'],size_bytes=r['size_bytes']) for r in rows.values() if r['status']=='approved for addition' and (r.get('size_bytes') or 0)>150000000],visitor_visible_changes=False,state='review_archives_complete_validation_pending')
save(F/'summary.json',summary)
cp=load(ROOT/'project-state/checkpoint.json');cp['counts_by_status']=inv['counts'];cp['recorded_at']=inv['generated_at'];cp['next_pending_id']=inv['next_pending_id'];cp['remaining_nonterminal']=sum(r['status'] in ['pending review','approved for addition','downloaded','parsed','description drafted','placement assigned'] or r['status']=='implemented' and r.get('validation_status')!='passed' for r in rows.values());cp['completed_item_range']='Background follow-up: 16 deterministic dispositions, 39 specific factual prerequisites, four unchanged owner packages; 16 exact archives';cp['resume_command']='Read CURRENT.md and background-followup-2026-09-26 authorization, summary, validation and integration receipts. Preserve unresolved factual prerequisites and owner packages; do not repeat uploads.';cp['background_followup']=dict(artifact=(F/'summary.json').relative_to(ROOT).as_posix(),state=summary['state'],resolved=summary['resolved_followups'],unresolved=summary['unresolved_followups'],archives=summary['exact_archives'],added_r2_bytes=summary['r2_added_bytes']);save(ROOT/'project-state/checkpoint.json',cp)
a['state']=summary['state'];save(F/'authorization.json',a)
save(F/'approved-archive-partition.json',dict(baseline_approved_count=len(a['approved_ids']),records=[dict(id=i,title=rows[i]['title'],status=rows[i]['status'],archive_receipt=next((r['key'] for r in receipts if r['id']==i),None),remaining_reason='Live maintained page; no static original' if rows[i]['status']=='approved for addition' and not rows[i].get('size_bytes') else '280024902-byte original exceeds per-object authorization' if rows[i]['status']=='approved for addition' else 'Exact original archive complete') for i in a['approved_ids']]))
report=['# Background follow-up and approved-original archive closeout','',f"Reviewed the exact 55-record queue. Resolved {summary['resolved_followups']} records deterministically; {len(remaining)} retain specific factual prerequisites. Four owner packages and all 11 owner rows are unchanged.",'',f"Archived {len(receipts)} unchanged originals with complete public GET size/SHA-256 verification. Added {summary['r2_added_bytes']} bytes; current R2 is {live['object_count']} objects / {live['total_bytes']} bytes. Remaining project capacity: {summary['storage_remaining_bytes']} bytes. No overwrites or deletions.",'','The 280024902-byte Sunport master plan remains above the 150000000-byte object limit. Live project pages have no static original to archive. The three old architecture holds were archived while canonical editorial placement remains unresolved. EHS metadata was corrected to Early Head Start from the actual response; no legal-compliance outcome was inferred.','','## Deterministic dispositions','']
report += [f"- {rows[i]['title']} (`{i}`): {d['rationale']}" for i,d in byid.items() if i in a['followup_ids'] and d['outcome']!='unresolved_evidence_prerequisite']
report += ['','## Remaining factual prerequisites','']+[f"- {r['title']} (`{r['id']}`): {r['required_evidence']}" for r in remaining]
(F/'report.md').write_text('\n'.join(report)+'\n',encoding='utf-8')
current=f'''# ABQInfo Current Work

The owner-authorized `background-followup-2026-09-26` task reviewed all 55 records in the separate Codex follow-up queue. Sixteen received deterministic dispositions: thirteen exclusions and three inventory-only approvals (two static originals archived and one live Mountain View drainage project page). Thirty-nine remain pending with exact source/family, provenance, minutes/cancellation or legal/finality prerequisites. They are not owner decisions and no uncertain outcome was inferred. Decisions and current official retrievals are saved in `{F.relative_to(ROOT).as_posix()}/`.

The four genuine owner packages and all eleven owner inventory rows are unchanged: fiber correspondence, contributed ART advocacy, six historical DPM proposals, and the wireless checklist. The exclusive mission-scope-borderline queue still has one record. The consolidated queue is regenerated from current inventory; no owner choice was applied.

All eligible currently approved static originals were archived: fourteen pre-existing approvals plus two resolved static follow-ups. Sixteen absent-key uploads added {summary['r2_added_bytes']} bytes, and each complete public GET matched exact official-source size and SHA-256. Current R2: {live['object_count']} objects / {live['total_bytes']} bytes; remaining ceiling capacity {summary['storage_remaining_bytes']} bytes. The 280024902-byte Sunport original remains above the 150000000-byte per-object authorization. {summary['approved_live_pages']} approved live pages have no static original to archive. The three old architecture holds retain unresolved canonical editorial placement after archival. No R2 deletion or overwrite occurred.

The EHS governance response concerns Early Head Start; the older Environmental Health Services title was corrected in inventory only. The National Guard table remains an attributed component with unexplained column abbreviations; its 172 assignments are not asserted to be unique personnel. Current 2024 bikeway bytes (513 pages) differ from the held 144-page original; provenance was preserved. API text responses whose returned matter ID did not match the requested matter were rejected. PGS enactment metadata still does not prove complete adopted delivery.

The refreshed ordinary queue is `{F.relative_to(ROOT).as_posix()}/next-ordinary-queue.json`: {q['pending_review_count']} pending, including {len(remaining)} Codex prerequisites, with existing unrelated protected/gated and live-service work unchanged. Review `{F.relative_to(ROOT).as_posix()}/summary.json`, validation and integration receipts before resuming. Review/archive stages are complete; full validation and authorized background integration/reconciliation remain pending.

No `content/`, layouts, assets, static resources or visitor-visible configuration changes occurred. Historical reassessment/campaign artifacts remain sealed; the new task has its own immutable baseline and population. Further ungated work requires the specific remaining source evidence, or a separate owner disposition of the four decision packages. Visible editorial work remains a separately reviewed stage.
'''
(ROOT/'project-state/CURRENT.md').write_text(current,encoding='utf-8')
print(summary)
