[CmdletBinding()]
param(
 [string]$ReportPath='project-state/discovery/live-abqinfo-archive-reconciliation-2026-09-16.json',[string]$MasterInventoryPath='project-state/master-inventory.json',[string]$R2InventoryPath='project-state/r2-inventory.json',[string]$OriginRef='origin/main',[string]$OutputPath='project-state/discovery/live-abqinfo-archive-reconciliation-classification-2026-09-16.json',[string]$ReviewPacketPath='project-state/discovery/live-abqinfo-archive-reconciliation-review-packet-2026-09-16.json')
$ErrorActionPreference='Stop'
function A($v){@($v)};function U($v){@(A $v|?{$_ -ne $null -and "$($_)" -ne ''}|%{"$($_)"}|sort -Unique)};function RunGit([string[]]$a){$o=& git @a 2>$null;if($LASTEXITCODE-ne 0){return ''};(($o-join "`n").Trim())};function Norm([string]$v){if([string]::IsNullOrWhiteSpace($v)){return $null};$s=$v.Trim();if($s-match'^https?://'){try{$s=([uri]$s).AbsolutePath}catch{}};return $s.TrimStart('/').ToLowerInvariant()};function Recs([string]$k){$n=Norm $k;if($masterByNorm.ContainsKey($n)){return @($masterByNorm[$n])};return @()}
$report=Get-Content $ReportPath -Raw|ConvertFrom-Json;$master=Get-Content $MasterInventoryPath -Raw|ConvertFrom-Json;$r2=Get-Content $R2InventoryPath -Raw|ConvertFrom-Json;$masterRecords=A $master.candidates;$r2Objects=A $r2.objects
$masterByNorm=@{};$keyByNorm=@{};foreach($m in $masterRecords){$n=Norm $m.r2_key;if(-not$n){$n=Norm $m.r2_url};if($n){if(-not$masterByNorm.ContainsKey($n)){$masterByNorm[$n]=[System.Collections.Generic.List[object]]::new()};$masterByNorm[$n].Add($m);if($m.r2_key){$keyByNorm[$n]=$m.r2_key}}};$r2ByNorm=@{};foreach($o in $r2Objects){$r2ByNorm[(Norm $o.key)]=$o}
$contentFiles=A ((RunGit @('ls-files','content'))-split "`n"|?{$_-match'\.md$'});$currentText=@{};$evidenceCache=@{};foreach($f in $contentFiles){$currentText[$f]=Get-Content $f -Raw -ErrorAction SilentlyContinue};$originBlob=RunGit @('grep','-n','files.abqinfo.com/',$OriginRef,'--','content');$historyByPath=@{};foreach($f in $contentFiles){$historyByPath[$f]=RunGit @('log','-1','--format=%h %s','--',$f)}
function Evidence([string]$key){$n=Norm $key;if($evidenceCache.ContainsKey($n)){return $evidenceCache[$n]};$needle="files.abqinfo.com/$n";$cp=@();foreach($f in $contentFiles){if($currentText[$f] -and $currentText[$f].IndexOf($needle,[StringComparison]::OrdinalIgnoreCase)-ge0){$cp+=$f}};$op=@();if($originBlob -and $originBlob.IndexOf($needle,[StringComparison]::OrdinalIgnoreCase)-ge0){$op+=('{0}:content' -f $OriginRef)};$historyPath=U $cp|Select-Object -First 1;$hist=if($historyPath){@($historyByPath[$historyPath])}else{@()};$e=[pscustomobject]@{normalized_key=$n;current_paths=U $cp;origin_paths=U $op;targeted_history=U $hist};$evidenceCache[$n]=$e;return $e}
$hashToNorm=@{};foreach($m in $masterRecords){$n=Norm $m.r2_key;if($n-and$m.checksum_sha256){$h=$m.checksum_sha256.ToLowerInvariant();if(-not$hashToNorm.ContainsKey($h)){$hashToNorm[$h]=[System.Collections.Generic.HashSet[string]]::new()};[void]$hashToNorm[$h].Add($n)}};$storageDuplicateGroups=@(foreach($h in $hashToNorm.Keys){$ns=@($hashToNorm[$h]);if($ns.Count-gt1){[pscustomobject]@{sha256=$h;r2_keys=@($ns|%{$keyByNorm[$_]});key_count=$ns.Count;master_record_ids=@(foreach($n in $ns){@(Recs $n|% id)})}}});$dupByNorm=@{};foreach($g in $storageDuplicateGroups){foreach($k in $g.r2_keys){$dupByNorm[(Norm k)]=$g}};foreach($g in $storageDuplicateGroups){$g | Add-Member -NotePropertyName key_evidence -NotePropertyValue (@(foreach($k in $g.r2_keys){[pscustomobject]@{key=$k;live_object_present=[bool]$r2ByNorm[(Norm $k)];content_evidence=(Evidence $k)}})) -Force}
$unref=A ($report.r2_objects|?{-not$_.published});$pub=A ($report.published_r2_links|?{$_.classification-eq'published_missing_repository_r2_record'});$expected=A ($report.expected_published_records|?{$_.classification-eq'expected_page_missing_live_link'});$sets=@{unreferenced=@($unref|%{Norm $_.key});published_missing_r2=@($pub|%{Norm $_.key});expected_not_live=@($expected|%{Norm $_.key})}
$tokenToGroup=@{};$next=0;function GroupFor($n,$ids){$t=@("k:$n")+@(A $ids|%{"i:$($_)"});$f=U($t|?{$tokenToGroup.ContainsKey($_)}|%{$tokenToGroup[$_]});if($f.Count-eq0){$g=('issue-{0:d4}'-f$script:next);$script:next++}else{$g=$f[0]};foreach($x in $t){$tokenToGroup[$x]=$g};return $g}
$cu=@(foreach($o in $unref){$n=Norm $o.key;$rs=Recs $n;$ev=Evidence $n;$repo=$r2ByNorm[$n];$dup=$dupByNorm[$n];$st=U ($rs|% status);$ids=@($rs|% id);$class='unreferenced_unaccounted_storage_candidate';$review=$true;$reason='No normalized master/repository record or content/history evidence accounts for this live object.';if($ev.current_paths.Count-gt0){$class='unreferenced_present_current_branch_pending_deployment';$review=$false;$reason='Exact R2 link is present in current repository content but absent from the live page crawl.'}elseif($dup){$class='unreferenced_storage_duplicate_of_other_r2_key';$reason='Different R2 keys share an exact recorded SHA-256; canonical/noncanonical retention requires review.'}elseif($rs.Count-gt0-and($st|?{$_-notin@('superseded','duplicate','excluded')}).Count-eq0){$class='unreferenced_intentionally_unpublished_noncanonical';$review=$false;$reason='Linked master records are all superseded, duplicate, or excluded.'}elseif($rs.Count-gt0-and$ev.origin_paths.Count-gt0){$class='unreferenced_known_master_pending_deployment';$review=$false;$reason='Origin/main contains an exact link, but it is absent from the live crawl.'}elseif($rs.Count-gt0){$class='unreferenced_known_master_publication_intent_unresolved';$reason='Active/validated master linkage exists without current/origin placement or live publication.'}elseif($repo){$class='unreferenced_repository_inventory_only';$reason='Repository R2 inventory contains the object without master/content linkage.'};$gid=GroupFor $n $ids;[pscustomobject]@{issue_group_id=$gid;key=$o.key;normalized_key=$n;public_url=$o.public_url;size_bytes=$o.size_bytes;etag=$o.etag;master_record_ids=$ids;master_statuses=$st;repository_r2_record_present=[bool]$repo;content_evidence=$ev;storage_duplicate_group=$dup;classification=$class;mechanically_resolvable=(-not$review);requires_human_review=$review;review_reason=$reason}})
$cp=@(foreach($p in $pub){$n=Norm $p.key;$rs=Recs $n;$ev=Evidence $n;$v=$p.verification;$size=($v.size_match-eq$true);$hash=($v.hash_match-eq$true);$ids=@($rs|% id);$class='published_object_unexplained';$review=$true;$reason='Published object is not explained by current/origin content, history, or normalized master metadata.';if($rs.Count-gt0-and($size-or$hash)){$class='published_object_missing_repository_r2_record_stale_inventory';$review=$false;$reason='Live object exactly matches recorded master size/hash; repository R2 inventory is stale.'}elseif($rs.Count-eq0-and($ev.current_paths.Count-gt0-or$ev.origin_paths.Count-gt0-or$ev.targeted_history.Count-gt0)){$class='published_legacy_object_missing_inventory_accounting';$review=$false;$reason='Published object has durable repository/origin/history reference evidence but no master record; inventory accounting is longstanding legacy drift.'}elseif($rs.Count-eq0){$class='published_object_without_master_record';$reason='Published object has no normalized master record and no durable repository/history evidence.'}else{$class='published_object_metadata_conflict';$reason='Normalized master linkage exists but exact live metadata agreement is unavailable.'};$gid=GroupFor $n $ids;[pscustomobject]@{issue_group_id=$gid;key=$p.key;normalized_key=$n;live_pages=$p.live_pages;live_size_bytes=$v.remote_size_bytes;master_record_ids=$ids;master_statuses=@($rs|% status);expected_sizes=$p.expected_sizes;expected_hashes=$p.expected_hashes;verification=$v;content_evidence=$ev;classification=$class;mechanically_resolvable=(-not$review);requires_human_review=$review;review_reason=$reason}})
$ce=@(foreach($e in $expected){$n=Norm $e.key;$rs=Recs $n;$ev=Evidence $n;$ids=@($rs|% id);if($ev.current_paths.Count-gt0){$class='expected_link_present_on_current_branch_not_live';$review=$false;$reason='Exact link is in current repository content but absent from live pages (deployment lag).'}elseif($ev.origin_paths.Count-gt0){$class='expected_link_present_on_origin_not_live';$review=$false;$reason='Exact link is on origin/main but absent from live pages (deployment lag).'}elseif($rs.Count-eq0){$class='expected_record_without_normalized_master_linkage';$review=$true;$reason='Expected record cannot be matched to normalized master metadata.'}else{$class='expected_link_absent_from_repository_content';$review=$true;$reason='Expected record has no current/origin exact link or history evidence.'};$gid=GroupFor $n $ids;[pscustomobject]@{issue_group_id=$gid;id=$e.id;title=$e.title;key=$e.key;normalized_key=$n;expected_pages=$e.expected_pages;missing_expected_pages=$e.missing_expected_pages;master_record_ids=$ids;master_statuses=@($rs|% status);content_evidence=$ev;classification=$class;mechanically_resolvable=(-not$review);requires_human_review=$review;review_reason=$reason}})
$all=@($cu+$cp+$ce);$counts=@{};foreach($i in $all){if(-not$counts.ContainsKey($i.classification)){$counts[$i.classification]=0};$counts[$i.classification]++};$groups=U($all|% issue_group_id);$reviews=U($all|? requires_human_review|% issue_group_id);$inter=@{unreferenced_and_published_missing_r2=@(U($sets.unreferenced|?{$sets.published_missing_r2-contains$_})).Count;unreferenced_and_expected_not_live=@(U($sets.unreferenced|?{$sets.expected_not_live-contains$_})).Count;published_missing_r2_and_expected_not_live=@(U($sets.published_missing_r2|?{$sets.expected_not_live-contains$_})).Count;all_three=@(U($sets.unreferenced|?{$sets.published_missing_r2-contains$_-and$sets.expected_not_live-contains$_})).Count};$overlap=[pscustomobject]@{raw_counts=@{unreferenced=$cu.Count;published_missing_r2_inventory=$cp.Count;expected_not_live=$ce.Count};unique_underlying_issue_groups=$groups.Count;unique_review_issue_groups=$reviews.Count;set_intersections=$inter;note='Groups connect normalized keys or master IDs; shared keys are record duplication, not storage duplication.'}
$out=[pscustomobject]@{schema_version='2.0';generated_at=(Get-Date).ToUniversalTime().ToString('o');inputs=[pscustomobject]@{report=$ReportPath;master_inventory=$MasterInventoryPath;r2_inventory=$R2InventoryPath;origin_ref=$OriginRef};summary=[pscustomobject]@{raw_discrepancies=$all.Count;unique_underlying_issue_groups=$groups.Count;unique_review_issue_groups=$reviews.Count;mechanically_resolvable=@($all|? mechanically_resolvable).Count;requires_human_review=@($all|? requires_human_review).Count;category_counts=$counts;actual_storage_duplicate_groups=$storageDuplicateGroups.Count};overlap=$overlap;storage_duplicate_groups=$storageDuplicateGroups;unreferenced_r2_objects=$cu;published_objects_missing_repository_r2_inventory=$cp;expected_but_not_live=$ce};$out|ConvertTo-Json -Depth 16|Set-Content $OutputPath -Encoding utf8;$packet=[pscustomobject]@{schema_version='2.0';generated_at=$out.generated_at;source_classification=$OutputPath;summary=[pscustomobject]@{raw_cases=@($all|? requires_human_review).Count;unique_issue_groups=$reviews.Count;storage_duplicate_groups=$storageDuplicateGroups.Count};cases=@($all|? requires_human_review|Group-Object issue_group_id|%{$_.Group|select -First 1})};$packet|ConvertTo-Json -Depth 16|Set-Content $ReviewPacketPath -Encoding utf8;Write-Output("Classified {0} raw discrepancies into {1} issue groups; {2} unique review groups."-f$all.Count,$groups.Count,$reviews.Count)









