[CmdletBinding()]
param(
  [string]$InventoryPath = 'project-state/master-inventory.json',
  [string]$OutputPath = 'project-state/ido-afr-history-decisions-2026-08-21.json'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$idoSource = 'https://www.cabq.gov/planning/codes-policies-regulations/integrated-development-ordinance-1/integrated-development-ordinance'
$afrSource = 'https://www.cabq.gov/fire/copy_of_reports'
$items = @(
  [ordered]@{url='https://documents.cabq.gov/planning/IDO/2025_IDO_Update/IDO_2025_Update_Effective-2026-04-20.pdf';title='Integrated Development Ordinance, Effective April 20, 2026';date='2026-04-20';key='development-land-use/zoning-ido/cabq-ido-effective-2026-04-20.pdf';page='content/development-land-use/zoning-ido.md';source=$idoSource;description='Preserves the consolidated Integrated Development Ordinance effective April 20, 2026, immediately before the May 2026 edition, documenting the zoning and development regulations applicable during that interval.'}
  [ordered]@{url='https://documents.cabq.gov/planning/IDO/O-25-73/IDO_2025_Update_Effective.pdf';title='Integrated Development Ordinance, Effective April 21, 2025';date='2025-04-21';key='development-land-use/zoning-ido/cabq-ido-effective-2025-04-21.pdf';page='content/development-land-use/zoning-ido.md';source=$idoSource;description='Preserves the consolidated Integrated Development Ordinance effective April 21, 2025, providing the authoritative zoning and development rules in force before the two 2026 effective editions.'}
  [ordered]@{url='https://documents.cabq.gov/planning/IDO/2023_IDO_AnnualUpdate/IDO_2023_AnnualUpdate_Effective.pdf';title='Integrated Development Ordinance, Effective August 3, 2024';date='2024-08-03';key='development-land-use/zoning-ido/cabq-ido-effective-2024-08-03.pdf';page='content/development-land-use/zoning-ido.md';source=$idoSource;description='Preserves the consolidated Integrated Development Ordinance effective August 3, 2024, recording Albuquerque zoning, subdivision, development-review, and dimensional regulations before the 2025 annual update.';large='The 28,857,956-byte comprehensive regulatory PDF contains extensive maps, diagrams, tables, and formatted code text. No smaller authoritative consolidated edition was found; optimization would alter the source, so the original is preserved unchanged.'}
  [ordered]@{url='https://documents.cabq.gov/planning/IDO/2022_IDO_AnnualUpdate/IDO-2022AnnualUpdate-EFFECTIVE-2023-07-27.pdf';title='Integrated Development Ordinance, Effective July 27, 2023';date='2023-07-27';key='development-land-use/zoning-ido/cabq-ido-effective-2023-07-27.pdf';page='content/development-land-use/zoning-ido.md';source=$idoSource;description='Preserves the consolidated Integrated Development Ordinance effective July 27, 2023, documenting the City zoning and development rules adopted through the 2022 annual update.'}
  [ordered]@{url='https://documents.cabq.gov/planning/IDO/2021_IDO_AnnualUpdate/IDO-2021AnnualUpdate-2022-12-25-Effective.pdf';title='Integrated Development Ordinance, Effective December 25, 2022';date='2022-12-25';key='development-land-use/zoning-ido/cabq-ido-effective-2022-12-25.pdf';page='content/development-land-use/zoning-ido.md';source=$idoSource;description='Preserves the consolidated Integrated Development Ordinance effective December 25, 2022, recording the zoning and development regulations adopted through the 2021 annual update.';large='The 44,150,591-byte comprehensive regulatory PDF contains extensive maps, diagrams, tables, and formatted code text. No smaller authoritative consolidated edition was found; optimization would alter the source, so the original is preserved unchanged.'}
  [ordered]@{url='https://documents.cabq.gov/planning/IDO/2020_IDO_AnnualUpdate/IDO-2020AnnualUpdate-2021-07-16-EffectiveDraft.pdf';title='Integrated Development Ordinance, Effective August 1, 2021';date='2021-08-01';key='development-land-use/zoning-ido/cabq-ido-effective-2021-08-01.pdf';page='content/development-land-use/zoning-ido.md';source=$idoSource;description='Preserves the City-posted consolidated Integrated Development Ordinance effective August 1, 2021, despite its legacy filename, documenting regulations adopted through the 2020 annual update.';large='The 37,257,141-byte comprehensive regulatory PDF contains extensive maps, diagrams, tables, and formatted code text. No smaller authoritative consolidated edition was found; optimization would alter the source, so the original is preserved unchanged.'}
  [ordered]@{url='https://documents.cabq.gov/planning/IDO/IDO-2019-Effective-2020-11-02.pdf';title='Integrated Development Ordinance, Effective November 2, 2020';date='2020-11-02';key='development-land-use/zoning-ido/cabq-ido-effective-2020-11-02.pdf';page='content/development-land-use/zoning-ido.md';source=$idoSource;description='Preserves the consolidated Integrated Development Ordinance effective November 2, 2020, providing the authoritative zoning and development rules following the 2019 annual update.'}
  [ordered]@{url='https://documents.cabq.gov/planning/IDO/IDO-Effective-2018-05-17.pdf';title='Integrated Development Ordinance, Effective May 17, 2018';date='2018-05-17';key='development-land-use/zoning-ido/cabq-ido-effective-2018-05-17.pdf';page='content/development-land-use/zoning-ido.md';source=$idoSource;description='Preserves Albuquerque’s first effective Integrated Development Ordinance, establishing the unified zoning, subdivision, and development-review framework that replaced the former zoning code and sector-plan system.'}
  [ordered]@{url='https://www.cabq.gov/fire/documents/2022-annual-report.pdf';title='Albuquerque Fire Rescue Annual Report, 2022';date='2022';key='city-data/public-safety/afr-annual-report-2022.pdf';page='content/city-data/public-safety-data.md';source=$afrSource;description='Reports Albuquerque Fire Rescue calls, response performance, staffing, stations, emergency medical services, fire prevention, community risk reduction, and major initiatives during calendar year 2022.'}
  [ordered]@{url='https://www.cabq.gov/fire/documents/2021-annual-report-interactive.pdf';title='Albuquerque Fire Rescue Annual Report, 2021';date='2021';key='city-data/public-safety/afr-annual-report-2021.pdf';page='content/city-data/public-safety-data.md';source=$afrSource;description='Reports Albuquerque Fire Rescue operations, incident demand, response performance, personnel, facilities, emergency medical work, prevention, and division accomplishments during calendar year 2021.'}
  [ordered]@{url='https://www.cabq.gov/fire/documents/2020-annual-report.pdf';title='Albuquerque Fire Rescue Annual Report, 2020';date='2020';key='city-data/public-safety/afr-annual-report-2020.pdf';page='content/city-data/public-safety-data.md';source=$afrSource;description='Documents Albuquerque Fire Rescue’s 2020 emergency response, call volumes, response times, staffing, stations, medical services, fire prevention, pandemic operations, and departmental accomplishments.';large='The 25,559,243-byte annual report is graphics-intensive and includes photographs, maps, charts, and formatted statistical material. No smaller authoritative City version was found; optimization would alter the source, so the original is preserved unchanged.'}
  [ordered]@{url='https://www.cabq.gov/fire/documents/annual-report-2019-final.pdf';title='Albuquerque Fire Rescue Annual Report, 2019';date='2019';key='city-data/public-safety/afr-annual-report-2019.pdf';page='content/city-data/public-safety-data.md';source=$afrSource;description='Documents Albuquerque Fire Rescue’s 2019 incident demand, response performance, personnel, stations, emergency medical services, prevention programs, fiscal information, and division accomplishments.';large='The 66,773,085-byte annual report is graphics-intensive and includes high-resolution photographs, maps, charts, and formatted statistical material. No smaller authoritative City version was found; optimization would alter the source, so the original is preserved unchanged.'}
  [ordered]@{url='https://www.cabq.gov/fire/documents/annual-report-2-corrected.pdf';title='Albuquerque Fire Rescue Annual Report, 2018';date='2018';key='city-data/public-safety/afr-annual-report-2018.pdf';page='content/city-data/public-safety-data.md';source=$afrSource;description='Documents Albuquerque Fire Rescue’s 2018 calls, response performance, personnel, facilities, medical services, prevention work, community programs, fiscal information, and organizational accomplishments.';large='The 27,475,969-byte corrected annual report is graphics-intensive and includes photographs, maps, charts, and formatted statistical material. No smaller authoritative City version was found; optimization would alter the source, so the original is preserved unchanged.'}
  [ordered]@{url='https://www.cabq.gov/fire/documents/abq-fire-2017-annual-report.pdf';title='Albuquerque Fire Department Annual Report, 2017';date='2017';key='city-data/public-safety/afd-annual-report-2017.pdf';page='content/city-data/public-safety-data.md';source=$afrSource;description='Documents the Albuquerque Fire Department’s 2017 emergency activity, response performance, personnel, stations, medical services, prevention, training, community programs, and departmental accomplishments.'}
  [ordered]@{url='https://www.cabq.gov/fire/documents/abq-fire-department-annual-report-2016.pdf';title='Albuquerque Fire Department Annual Report, 2016';date='2016';key='city-data/public-safety/afd-annual-report-2016.pdf';page='content/city-data/public-safety-data.md';source=$afrSource;description='Documents the Albuquerque Fire Department’s 2016 incident demand, response performance, staffing, stations, emergency medical services, prevention, training, community programs, and organizational accomplishments.'}
  [ordered]@{url='https://www.cabq.gov/fire/documents/2015-albuquerque-fire-department-annual-report.pdf';title='Albuquerque Fire Department Annual Report, 2015';date='2015';key='city-data/public-safety/afd-annual-report-2015.pdf';page='content/city-data/public-safety-data.md';source=$afrSource;description='Documents the Albuquerque Fire Department’s 2015 calls, response performance, personnel, facilities, emergency medical work, prevention, training, community programs, and departmental accomplishments.'}
  [ordered]@{url='https://www.cabq.gov/fire/documents/2014-albuquerque-fire-department-annual-report.pdf';title='Albuquerque Fire Department Annual Report, 2014';date='2014';key='city-data/public-safety/afd-annual-report-2014.pdf';page='content/city-data/public-safety-data.md';source=$afrSource;description='Documents the Albuquerque Fire Department’s 2014 emergency activity, response performance, staffing, stations, medical services, prevention, training, public education, and organizational accomplishments.'}
)

$decisions = @()
foreach ($item in $items) {
  $record = & "$PSScriptRoot/Add-InventoryCandidate.ps1" -SourceUrl $item.url -DirectFileUrl $item.url -Agency 'City of Albuquerque' -Title $item.title -Date $item.date -FileType PDF -ParentUrl $item.source -DiscoveryMethod 'official archive lineage link' -CrawlDepth 1 -InventoryPath $InventoryPath | ConvertFrom-Json
  $decision = [ordered]@{
    id=$record.id; title=$item.title; date=$item.date; r2_key=$item.key
    canonical_page=$item.page; source_page=$item.source; direct_file_url=$item.url
    agency='City of Albuquerque'; description=$item.description; decision='approved for addition'
    provenance_status='official City archive page and direct government PDF recorded'
    processing_notes=@('Original authoritative City PDF will be preserved without modification; exact size and SHA-256 are recorded after download.')
  }
  if ($item.Contains('large') -and $item.large) { $decision.large_file_assessment = $item.large }
  $decisions += [pscustomobject]$decision
}

[ordered]@{batch_id='2026-08-21-ido-afr-history';decisions=$decisions} | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $OutputPath -Encoding utf8
[pscustomobject]@{Items=$decisions.Count;OutputPath=$OutputPath;Ids=@($decisions.id)} | ConvertTo-Json -Depth 4
