[CmdletBinding()]param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
. "$PSScriptRoot/ParallelVerification.Campaign.Common.ps1"

function Assert-CampaignTest([bool]$Condition,[string]$Message){if(-not$Condition){throw "Campaign workflow test failed: $Message"}}
function Set-CampaignTestJson($Value,[string]$Path,[switch]$ReadOnly){$parent=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};if(Test-Path -LiteralPath $Path){[IO.File]::SetAttributes($Path,[IO.FileAttributes]::Normal)};[IO.File]::WriteAllText($Path,($Value|ConvertTo-Json -Depth 40),[Text.UTF8Encoding]::new($false));if($ReadOnly){[IO.File]::SetAttributes($Path,[IO.FileAttributes]::ReadOnly)}}
function New-CampaignTestCandidate([string]$Id){[pscustomobject][ordered]@{id=$Id;status='pending review';source_url="https://www.cabq.gov/test/$Id";direct_file_url=$null;r2_url=$null;r2_key=$null;r2_etag=$null;r2_last_modified=$null;agency='City of Albuquerque';title="Fixture $Id";date='2026-09-10';file_type='Web page';size_bytes=$null;checksum_sha256=$null;parent_url='https://www.cabq.gov/test';referring_urls=@('https://www.cabq.gov/test');discovery_path=@('fixture');discovery_method='campaign fixture';crawl_depth=0;cited_predecessors=@();cited_successors=@();provenance_status='verified official source';proposed_canonical_page=$null;description=$null;description_word_count=0;processing_notes=@('Fixture candidate.');implementation_location=$null;implementation_locations=@();cross_listing_approved=$false;validation_status='pending';exclusion_reason=$null;local_path=$null;discovered_at='2026-09-10T00:00:00Z';updated_at='2026-09-10T00:00:00Z'}}

$testRoot=Join-Path ([IO.Path]::GetTempPath()) ('abqinfo-campaign-tests-'+[guid]::NewGuid().ToString('N'));$inventoryPath=Join-Path $testRoot 'master-inventory.json';$campaignRoot=Join-Path $testRoot 'campaigns';$activePath=Join-Path $testRoot 'active-run.json';$leasePath=Join-Path $testRoot 'writer.lock';$tests=[Collections.Generic.List[string]]::new()
try{
  New-Item -ItemType Directory -Path $testRoot -Force|Out-Null
  $ids=1..8|ForEach-Object{'src-{0:d16}' -f $_};$candidates=@($ids|ForEach-Object{New-CampaignTestCandidate $_})
  $inventory=[pscustomobject][ordered]@{schema_version=1;generated_at='2026-09-10T00:00:00Z';next_pending_id=$ids[0];allowed_statuses=@('pending review','approved for addition','downloading','downloaded','parsed','description drafted','placement assigned','implemented','validated','excluded','duplicate','superseded','blocked','requires human review');counts=[pscustomobject]@{'pending review'=8};candidates=$candidates};Set-CampaignTestJson $inventory $inventoryPath
  $head=(& git rev-parse HEAD).Trim();$created=& "$PSScriptRoot/New-ParallelVerificationCampaign.ps1" -CampaignId 'fixture-campaign' -LaneIds codex,claude -CandidateIds $ids -MicrobatchSize 2 -InventoryPath $inventoryPath -CampaignRoot $campaignRoot -BaseCommit $head|ConvertFrom-Json;$manifestPath=[string]$created.manifest_path;$campaign=Read-ParallelVerificationJson $manifestPath
  Assert-CampaignTest ($campaign.batches.Count-eq4 -and $campaign.batches[0].lane_id-eq'codex' -and $campaign.batches[1].lane_id-eq'claude') 'deterministic microbatch/lane assignment failed.';Assert-CampaignTest (((Get-Item $manifestPath).Attributes-band[IO.FileAttributes]::ReadOnly)-ne0) 'campaign manifest is not immutable.';$tests.Add('immutable-deterministic-campaign')
  $overlapBlocked=$false;try{& "$PSScriptRoot/New-ParallelVerificationCampaign.ps1" -CampaignId 'overlap-campaign' -LaneIds codex,claude -CandidateIds $ids[0] -MicrobatchSize 1 -InventoryPath $inventoryPath -CampaignRoot $campaignRoot -BaseCommit $head|Out-Null}catch{$overlapBlocked=$true};Assert-CampaignTest $overlapBlocked 'cross-campaign overlap was not rejected.';$tests.Add('cross-campaign-overlap-detection')
  $plan=& "$PSScriptRoot/Initialize-ParallelVerificationCampaignWorktrees.ps1" -ManifestPath $manifestPath -WorktreeRoot (Join-Path ([IO.Path]::GetTempPath()) 'abqinfo-campaign-worktrees') -PlanOnly|ConvertFrom-Json;Assert-CampaignTest ($plan.worktrees.Count-eq2) 'lane worktree plan is incomplete.';$tests.Add('detached-lane-worktree-plan')
  & "$PSScriptRoot/Set-ActiveParallelVerificationCampaign.ps1" -ManifestPath $manifestPath -ActiveRunPath $activePath|Out-Null;$initial=& "$PSScriptRoot/Get-ParallelVerificationCampaignStatus.ps1" -ActiveRunPath $activePath -InventoryPath $inventoryPath|ConvertFrom-Json;Assert-CampaignTest ($initial.valid -and $initial.remaining-eq8) 'active campaign pointer/status failed.';$tests.Add('active-pointer-and-derived-status')
  $firstEntry=@(Get-ParallelVerificationCampaignEntries $campaign)[0];$firstResultPath=Join-Path (Split-Path -Parent $manifestPath) $firstEntry.result_path;$orphanTemp=Join-Path (Split-Path -Parent $firstResultPath) ('.'+[IO.Path]::GetFileName($firstResultPath)+'.tmp-interrupted');New-Item -ItemType Directory -Path (Split-Path -Parent $orphanTemp) -Force|Out-Null;[IO.File]::WriteAllText($orphanTemp,'{"partial":',[Text.UTF8Encoding]::new($false))

  foreach($phase in @('before-verification','after-verification-before-result')){$stopped=$false;try{& "$PSScriptRoot/Invoke-ParallelVerificationCampaignWorker.ps1" -ManifestPath $manifestPath -LaneId codex -WorkerProvider codex -RepoRoot $testRoot -SkipLinkCheck -TestInterruptAt $phase|Out-Null}catch{$stopped=$true};Assert-CampaignTest $stopped "worker did not stop at $phase"}
  $status=& "$PSScriptRoot/Get-ParallelVerificationCampaignStatus.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath|ConvertFrom-Json;Assert-CampaignTest ($status.verified-eq0) 'pre-result interruptions persisted a completed result.';$tests.Add('interrupt-before-and-during-verification')
  & "$PSScriptRoot/Invoke-ParallelVerificationCampaignWorker.ps1" -ManifestPath $manifestPath -LaneId codex -WorkerProvider codex -RepoRoot $testRoot -SkipLinkCheck -MaxCandidates 1|Out-Null
  Assert-CampaignTest ((Test-Path -LiteralPath $firstResultPath) -and (Test-Path -LiteralPath $orphanTemp)) 'an orphaned temporary write blocked atomic result publication.';$tests.Add('atomic-publication-ignores-orphaned-temporary-file')
  $stopped=$false;try{& "$PSScriptRoot/Invoke-ParallelVerificationCampaignWorker.ps1" -ManifestPath $manifestPath -LaneId codex -WorkerProvider codex -RepoRoot $testRoot -SkipLinkCheck -TestInterruptAt after-batch|Out-Null}catch{$stopped=$true};Assert-CampaignTest $stopped 'batch-transition interruption did not fire.'
  $stopped=$false;try{& "$PSScriptRoot/Invoke-ParallelVerificationCampaignWorker.ps1" -ManifestPath $manifestPath -LaneId codex -WorkerProvider codex -RepoRoot $testRoot -SkipLinkCheck -TestInterruptAt after-result|Out-Null}catch{$stopped=$true};Assert-CampaignTest $stopped 'post-result interruption did not fire.'
  & "$PSScriptRoot/Invoke-ParallelVerificationCampaignWorker.ps1" -ManifestPath $manifestPath -LaneId codex -WorkerProvider codex -RepoRoot $testRoot -SkipLinkCheck|Out-Null
  $status=& "$PSScriptRoot/Get-ParallelVerificationCampaignStatus.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath|ConvertFrom-Json;Assert-CampaignTest ($status.lanes|Where-Object lane_id -eq codex|Select-Object -ExpandProperty complete)-eq4 'Codex lane did not resume across candidate and batch interruptions.';$tests.Add('candidate-and-batch-resumption')

  $claudeLease=Join-Path (Split-Path -Parent $manifestPath) 'leases/claude.json';Set-CampaignTestJson ([ordered]@{schema_version=1;campaign_id='fixture-campaign';lane_id='claude';owner_token='old';worker_provider='claude';pid=1;state='active';heartbeat_at='2026-01-01T00:00:00Z';expires_at='2026-01-01T00:01:00Z'}) $claudeLease
  $locked=[IO.File]::Open($claudeLease,[IO.FileMode]::Open,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);$contention=$false;try{try{& "$PSScriptRoot/Invoke-ParallelVerificationCampaignWorker.ps1" -ManifestPath $manifestPath -LaneId claude -WorkerProvider claude -RepoRoot $testRoot -SkipLinkCheck -TakeOverExpiredLease|Out-Null}catch{$contention=$true}}finally{$locked.Dispose()};Assert-CampaignTest $contention 'simultaneous lane ownership was not rejected.'
  & "$PSScriptRoot/Invoke-ParallelVerificationCampaignWorker.ps1" -ManifestPath $manifestPath -LaneId claude -WorkerProvider claude -RepoRoot $testRoot -SkipLinkCheck -TakeOverExpiredLease -MaxCandidates 1|Out-Null
  $originalInventory=[IO.File]::ReadAllText($inventoryPath);$stale=$originalInventory|ConvertFrom-Json;$stale.candidates[3].title='changed';Set-CampaignTestJson $stale $inventoryPath;$staleStatus=& "$PSScriptRoot/Get-ParallelVerificationCampaignStatus.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath|ConvertFrom-Json;Assert-CampaignTest (-not$staleStatus.valid -and @($staleStatus.errors|Where-Object{$_-match'Stale pending candidate'}).Count-gt0) 'stale pending input was not detected.';[IO.File]::WriteAllText($inventoryPath,$originalInventory,[Text.UTF8Encoding]::new($false))
  & "$PSScriptRoot/Invoke-ParallelVerificationCampaignWorker.ps1" -ManifestPath $manifestPath -LaneId claude -WorkerProvider codex-takeover -RepoRoot $testRoot -SkipLinkCheck|Out-Null
  $status=& "$PSScriptRoot/Get-ParallelVerificationCampaignStatus.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath|ConvertFrom-Json;Assert-CampaignTest ($status.verified-eq8 -and $status.remaining-eq0) 'provider-neutral lane takeover did not finish the campaign.';$tests.Add('lease-contention-expiry-stale-and-provider-takeover')

  $entries=@(Get-ParallelVerificationCampaignEntries $campaign);$tamperPath=Join-Path (Split-Path -Parent $manifestPath) $entries[0].result_path;$originalResult=[IO.File]::ReadAllText($tamperPath);$tampered=$originalResult|ConvertFrom-Json;$tampered.worker_provider='tampered';Set-CampaignTestJson $tampered $tamperPath -ReadOnly;$tamperStatus=& "$PSScriptRoot/Get-ParallelVerificationCampaignStatus.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath|ConvertFrom-Json;Assert-CampaignTest (-not$tamperStatus.valid) 'tampered result was not rejected.';[IO.File]::SetAttributes($tamperPath,[IO.FileAttributes]::Normal);[IO.File]::WriteAllText($tamperPath,$originalResult,[Text.UTF8Encoding]::new($false));[IO.File]::SetAttributes($tamperPath,[IO.FileAttributes]::ReadOnly)
  $originalManifest=[IO.File]::ReadAllText($manifestPath);$bad=Read-ParallelVerificationJson $manifestPath;$bad.batches[1].candidates=@($bad.batches[1].candidates)+@($bad.batches[0].candidates[0]);$bad.candidate_count=9;$bad.campaign_sha256=Get-ParallelVerificationObjectHash (Get-ParallelVerificationCampaignPayload $bad);$badErrors=@(Test-ParallelVerificationCampaignObject $bad);Assert-CampaignTest (@($badErrors|Where-Object{$_-match'overlap'}).Count-gt0) 'within-campaign overlap was not rejected.';$tests.Add('tamper-and-within-campaign-overlap-detection')

  $failedAcceptanceBlocked=$false;try{& "$PSScriptRoot/Merge-ParallelVerificationCampaign.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath -AcceptedCandidateIds $ids[7]|Out-Null}catch{$failedAcceptanceBlocked=$true};Assert-CampaignTest $failedAcceptanceBlocked 'incomplete result was accepted without a master review decision.'
  $decisionPath=Join-Path $testRoot 'decision.json';Set-CampaignTestJson ([ordered]@{campaign_id='fixture-campaign';campaign_sha256=[string]$campaign.campaign_sha256;decisions=@([ordered]@{candidate_id=$ids[7];accepted=$true;proposed_updates=[ordered]@{status='requires human review';validation_status='requires human review: fixture';processing_notes_append='Fixture ambiguity.'};decision_notes='Fixture master decision.'})}) $decisionPath
  $reviewDry=& "$PSScriptRoot/Merge-ParallelVerificationCampaign.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath -AcceptedCandidateIds $ids[7] -DecisionPath $decisionPath|ConvertFrom-Json;Assert-CampaignTest ($reviewDry.mode-eq'dry-run') 'documented requires-human-review decision was rejected.';$tests.Add('master-controlled-ambiguity-decision')

  foreach($entry in $entries){$path=Join-Path (Split-Path -Parent $manifestPath) $entry.result_path;$result=Read-ParallelVerificationJson $path;$result.checks.link_reachability.status='passed';$result.checks.link_reachability.http_status=200;$result.checks.link_reachability.reason='Fixture pass.';$result.overall_status='passed';$result.result_sha256=Get-ParallelVerificationObjectHash (Get-ParallelVerificationCandidateResultPayload $result);Set-CampaignTestJson $result $path -ReadOnly}
  $passing=& "$PSScriptRoot/Get-ParallelVerificationCampaignStatus.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath|ConvertFrom-Json;Assert-CampaignTest ($passing.valid -and $passing.passed-eq8) 'passing results did not validate.'
  $dryHash=Get-ParallelVerificationFileHash $inventoryPath;$dry=& "$PSScriptRoot/Merge-ParallelVerificationCampaign.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath -AcceptedCandidateIds $ids[0] -LeasePath $leasePath|ConvertFrom-Json;Assert-CampaignTest ($dry.mode-eq'dry-run' -and (Get-ParallelVerificationFileHash $inventoryPath)-eq$dryHash) 'integration dry-run modified inventory.'
  Set-CampaignTestJson ([ordered]@{expires_at=(Get-Date).ToUniversalTime().AddMinutes(5).ToString('o')}) $leasePath;$writerLock=[IO.File]::Open($leasePath,[IO.FileMode]::Open,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);$blocked=$false;try{try{& "$PSScriptRoot/Merge-ParallelVerificationCampaign.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath -AcceptedCandidateIds $ids[0] -Apply -TakeOverExpiredLease -LeasePath $leasePath|Out-Null}catch{$blocked=$true}}finally{$writerLock.Dispose()};Assert-CampaignTest $blocked 'concurrent inventory writer was not rejected.';Remove-Item -LiteralPath $leasePath -Force
  Set-CampaignTestJson ([ordered]@{expires_at='2026-01-01T00:00:00Z'}) $leasePath;$stopped=$false;try{& "$PSScriptRoot/Merge-ParallelVerificationCampaign.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath -AcceptedCandidateIds $ids[0] -Apply -TakeOverExpiredLease -LeasePath $leasePath -TestInterruptAt after-intent|Out-Null}catch{$stopped=$true};Assert-CampaignTest ($stopped -and (Test-Path (Join-Path (Split-Path -Parent $manifestPath) "integration/intents/$($ids[0]).json")) -and (Get-ParallelVerificationFileHash $inventoryPath)-eq$dryHash) 'write-ahead interruption was not recoverable.'
  $stopped=$false;try{& "$PSScriptRoot/Merge-ParallelVerificationCampaign.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath -AcceptedCandidateIds $ids[0] -Apply -LeasePath $leasePath -TestInterruptAt after-update-before-receipt|Out-Null}catch{$stopped=$true};$afterUpdate=Read-ParallelVerificationJson $inventoryPath;Assert-CampaignTest ($stopped -and @($afterUpdate.candidates[0].processing_notes|Where-Object{$_-match'^Parallel verification operation '}).Count-eq1) 'post-update interruption lost the idempotency marker.'
  & "$PSScriptRoot/Merge-ParallelVerificationCampaign.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath -AcceptedCandidateIds $ids[0] -Apply -LeasePath $leasePath|Out-Null;$receiptPath=Join-Path (Split-Path -Parent $manifestPath) "integration/receipts/$($ids[0]).json";$receipt=Read-ParallelVerificationJson $receiptPath;Assert-CampaignTest $receipt.recovery 'missing receipt was not recovered after an applied update.'
  & "$PSScriptRoot/Merge-ParallelVerificationCampaign.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath -AcceptedCandidateIds $ids[0] -Apply -LeasePath $leasePath|Out-Null;$finalInventory=Read-ParallelVerificationJson $inventoryPath;Assert-CampaignTest (@($finalInventory.candidates[0].processing_notes|Where-Object{$_-match'^Parallel verification operation '}).Count-eq1) 'repeated integration duplicated an accepted operation.'
  $stopped=$false;try{& "$PSScriptRoot/Merge-ParallelVerificationCampaign.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath -AcceptedCandidateIds $ids[1] -Apply -LeasePath $leasePath -TestInterruptAt after-receipt|Out-Null}catch{$stopped=$true};Assert-CampaignTest ($stopped -and (Test-Path (Join-Path (Split-Path -Parent $manifestPath) "integration/receipts/$($ids[1]).json"))) 'post-receipt interruption did not preserve completion.';& "$PSScriptRoot/Merge-ParallelVerificationCampaign.ps1" -ManifestPath $manifestPath -InventoryPath $inventoryPath -AcceptedCandidateIds $ids[1] -Apply -LeasePath $leasePath|Out-Null
  $finalStatus=& "$PSScriptRoot/Get-ParallelVerificationCampaignStatus.ps1" -ActiveRunPath $activePath -InventoryPath $inventoryPath|ConvertFrom-Json;Assert-CampaignTest ($finalStatus.valid -and $finalStatus.accepted-eq2 -and $finalStatus.integrated-eq2) 'derived acceptance/integration status is incorrect.';$tests.Add('crash-safe-idempotent-single-writer-integration')
  [pscustomobject][ordered]@{passed=$true;test_count=$tests.Count;tests=@($tests)}|ConvertTo-Json -Depth 6
}finally{if(Test-Path -LiteralPath $testRoot){Get-ChildItem -LiteralPath $testRoot -Recurse -Force -File|ForEach-Object{$_.Attributes=[IO.FileAttributes]::Normal};Remove-Item -LiteralPath $testRoot -Recurse -Force}}
