"""Save confirmed new-source findings while actual Chrome rendering remains pending."""
import sys,subprocess
sys.path.insert(0,'scripts/project');import OwnerResources20261004 as S
P=S.prefix(S.B);rows={x['id']:x for x in S.G.load('project-state/master-inventory.json')['candidates']}
directory=S.NEW[1];app=S.NEW[0]
scope=dict(assessed_at='2026-10-04',geographic_institutional_scope='City Office of Neighborhood Coordination recognized Albuquerque neighborhood associations.',specific_albuquerque_connection='The actual directory links websites submitted by named recognized Albuquerque associations and coalitions, including Barelas, Downtown, Nob Hill and neighborhood organizations throughout the City.',abqinfo_public_information_value='Provides a concise gateway to neighborhood organizations participating in City civic and development processes, complementing the existing ONC task-force and facilitated-meetings records.',general_context_exclusion_test='The actual resource identifies recognized local organizations and directs readers to their own sites; it is substantive Albuquerque civic participation information, not general municipal context, unrelated jurisdiction or transactional paperwork.',final_scope_decision='passes_both_gates',substantive_rationale='The maintained City directory materially helps readers locate recognized local neighborhood organizations and their association websites. This is a current civic reference adjacent to existing neighborhood participation and development-review materials. One live directory entry provides useful access without copying a changing roster or creating redundant association entries.')
requirement='Approve the exact owner-supplied ONC Neighborhood Association Websites URL as one live-directory resource under Development Process / Current City Review Process. Describe direct access to recognized associations that submitted websites; exclude HOA websites and clarify associations maintain their own sites. No standalone page or copied roster. Link to the reviewed neighborhood map by internal cross-reference only if that map is actually rendered and approved; no duplicate directory entry. Actual visual quality/preview review remains pending before final implemented status.'
S.G.write_once(P+'review.json',dict(artifact_type='owner_new_resource_source_findings',directory=dict(candidate_id=directory,title='Neighborhood Association Websites',scope_assessment=scope,binding_requirement=requirement,source_evidence=P+'evidence-1.json',substantive_scope='passes_both_gates',visual_quality='pending actual rendered inspection'),arcgis=dict(candidate_id=app,title=S.G.load(P+'evidence-2.json')['item']['title'],title_evidence=P+'evidence-2.json',rendered_usability='pending',substantive_disposition='pending actual desktop Chrome review')))
S.bind(P+'review.json','decision-'+S.B+'-neighborhood-directory',requirement,dict(candidate_ids=[directory],task_ids=[S.B],pages=['content/development-land-use/development-process.md']))
updates=[dict(id=directory,changes=dict(status='approved for addition',scope_assessment=scope,proposed_canonical_page='content/development-land-use/development-process.md',description='Direct access to websites submitted by City-recognized neighborhood associations; excludes HOA websites. Associations maintain their own sites.',provenance_status='Exact maintained official City ONC directory freshly retrieved; explicit submitted-site and HOA limitations verified.',validation_status='Scope and live-directory value approved; visual quality and publication preview inspection pending.',processing_notes=rows[directory]['processing_notes']+['2026-10-04 current official directory contents reviewed: recognized associations only, submitted websites, no HOA websites; positive Albuquerque civic-value assessment saved in '+P+'review.json.'])),dict(id=app,changes=dict(title=S.G.load(P+'evidence-2.json')['item']['title'],provenance_status='Authoritative City agis_CABQ application title and configuration retrieved; actual desktop rendering remains pending.',processing_notes=rows[app]['processing_notes']+['2026-10-04 official metadata identifies Recognized Neighborhood Associations and Coalitions, webmap183fc71a9ed0404fba6d29fe9e9bf6ac. Metadata alone does not establish actual visible data/usability; review is pending requested desktop Chrome control.']))]
S.save(P+'new-source-updates.json',updates);S.refresh(S.B)
subprocess.run([sys.executable,'scripts/project/Update-CandidatesBatch.py','--requests',P+'new-source-updates.json'],check=True)
S.event(S.B,'document_review',[directory],'Reviewed actual official ONC directory text and scope; visual quality remains pending.',P+'review.json')
S.event(S.B,'document_review',[app],'Retrieved authoritative City app identity; no usability or publication approval inferred from metadata.',P+'evidence-2.json')
S.refresh(S.B)
